; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py
; RUN: opt -mtriple=riscv64 -mattr=+v -passes="print<cost-model>" 2>&1 \
; RUN:   -disable-output < %s | FileCheck %s --check-prefix=NOZVCD
; RUN: opt -mtriple=riscv64 -mattr=+v,+experimental-zvcd \
; RUN:   -passes="print<cost-model>" 2>&1 -disable-output < %s \
; RUN:   | FileCheck %s --check-prefix=ZVCD

;; Without Zvcd the 'add' histogram intrinsic has an invalid cost, which keeps
;; the loop vectorizer from generating it.  With Zvcd it gets a finite cost (a
;; masked gather + masked scatter plus the vconflictcnt.v conflict-count work).
;; Element types that are not legal for RVV gather/scatter, and the other
;; histogram updates (which are not lowered with Zvcd), stay invalid.

define void @histogram_add_i32(<vscale x 4 x ptr> %buckets, i32 %inc, <vscale x 4 x i1> %mask) {
; NOZVCD-LABEL: 'histogram_add_i32'
; NOZVCD-NEXT:  Cost Model: Invalid cost for instruction: call void @llvm.experimental.vector.histogram.add.nxv4p0.i32(<vscale x 4 x ptr> %buckets, i32 %inc, <vscale x 4 x i1> %mask)
; NOZVCD-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; ZVCD-LABEL: 'histogram_add_i32'
; ZVCD-NEXT:  Cost Model: Found an estimated cost of {{[0-9]+}} for instruction: call void @llvm.experimental.vector.histogram.add.nxv4p0.i32(<vscale x 4 x ptr> %buckets, i32 %inc, <vscale x 4 x i1> %mask)
; ZVCD-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
  call void @llvm.experimental.vector.histogram.add.nxv4p0.i32(<vscale x 4 x ptr> %buckets, i32 %inc, <vscale x 4 x i1> %mask)
  ret void
}

define void @histogram_add_i64(<vscale x 2 x ptr> %buckets, i64 %inc, <vscale x 2 x i1> %mask) {
; NOZVCD-LABEL: 'histogram_add_i64'
; NOZVCD-NEXT:  Cost Model: Invalid cost for instruction: call void @llvm.experimental.vector.histogram.add.nxv2p0.i64(<vscale x 2 x ptr> %buckets, i64 %inc, <vscale x 2 x i1> %mask)
; NOZVCD-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; ZVCD-LABEL: 'histogram_add_i64'
; ZVCD-NEXT:  Cost Model: Found an estimated cost of {{[0-9]+}} for instruction: call void @llvm.experimental.vector.histogram.add.nxv2p0.i64(<vscale x 2 x ptr> %buckets, i64 %inc, <vscale x 2 x i1> %mask)
; ZVCD-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
  call void @llvm.experimental.vector.histogram.add.nxv2p0.i64(<vscale x 2 x ptr> %buckets, i64 %inc, <vscale x 2 x i1> %mask)
  ret void
}

;; i8 buckets are not a supported Zvcd SEW, so the cost stays invalid.
define void @histogram_add_i8(<vscale x 4 x ptr> %buckets, i8 %inc, <vscale x 4 x i1> %mask) {
; NOZVCD-LABEL: 'histogram_add_i8'
; NOZVCD-NEXT:  Cost Model: Invalid cost for instruction: call void @llvm.experimental.vector.histogram.add.nxv4p0.i8(<vscale x 4 x ptr> %buckets, i8 %inc, <vscale x 4 x i1> %mask)
; NOZVCD-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; ZVCD-LABEL: 'histogram_add_i8'
; ZVCD-NEXT:  Cost Model: Invalid cost for instruction: call void @llvm.experimental.vector.histogram.add.nxv4p0.i8(<vscale x 4 x ptr> %buckets, i8 %inc, <vscale x 4 x i1> %mask)
; ZVCD-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
  call void @llvm.experimental.vector.histogram.add.nxv4p0.i8(<vscale x 4 x ptr> %buckets, i8 %inc, <vscale x 4 x i1> %mask)
  ret void
}

;; The idempotent umin/umax updates are not lowered with Zvcd, so their cost
;; stays invalid (they are left for the generic scalarizer).
define void @histogram_umax_i32(<vscale x 4 x ptr> %buckets, i32 %inc, <vscale x 4 x i1> %mask) {
; NOZVCD-LABEL: 'histogram_umax_i32'
; NOZVCD-NEXT:  Cost Model: Invalid cost for instruction: call void @llvm.experimental.vector.histogram.umax.nxv4p0.i32(<vscale x 4 x ptr> %buckets, i32 %inc, <vscale x 4 x i1> %mask)
; NOZVCD-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; ZVCD-LABEL: 'histogram_umax_i32'
; ZVCD-NEXT:  Cost Model: Invalid cost for instruction: call void @llvm.experimental.vector.histogram.umax.nxv4p0.i32(<vscale x 4 x ptr> %buckets, i32 %inc, <vscale x 4 x i1> %mask)
; ZVCD-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
  call void @llvm.experimental.vector.histogram.umax.nxv4p0.i32(<vscale x 4 x ptr> %buckets, i32 %inc, <vscale x 4 x i1> %mask)
  ret void
}
