// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv64 -target-feature +v \
// RUN:   -target-feature +experimental-zvcd -disable-O0-optnone \
// RUN:   -emit-llvm %s -o - | opt -S -passes=mem2reg | \
// RUN:   FileCheck --check-prefix=CHECK-RV64 %s

#include <riscv_vector.h>

// CHECK-RV64-LABEL: @test_vconflictlast_v_i32mf2_b64(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i1> @llvm.riscv.vconflictlast.nxv1i32.i64(<vscale x 1 x i1> poison, <vscale x 1 x i32> [[VS2:%.*]], i64 [[VL:%.*]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i1> [[TMP0]]
//
vbool64_t test_vconflictlast_v_i32mf2_b64(vint32mf2_t vs2, size_t vl) {
  return __riscv_vconflictlast_v_i32mf2_b64(vs2, vl);
}

// CHECK-RV64-LABEL: @test_vconflictlast_v_i32m1_b32(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i1> @llvm.riscv.vconflictlast.nxv2i32.i64(<vscale x 2 x i1> poison, <vscale x 2 x i32> [[VS2:%.*]], i64 [[VL:%.*]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i1> [[TMP0]]
//
vbool32_t test_vconflictlast_v_i32m1_b32(vint32m1_t vs2, size_t vl) {
  return __riscv_vconflictlast_v_i32m1_b32(vs2, vl);
}

// CHECK-RV64-LABEL: @test_vconflictlast_v_i32m2_b16(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vconflictlast.nxv4i32.i64(<vscale x 4 x i1> poison, <vscale x 4 x i32> [[VS2:%.*]], i64 [[VL:%.*]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i1> [[TMP0]]
//
vbool16_t test_vconflictlast_v_i32m2_b16(vint32m2_t vs2, size_t vl) {
  return __riscv_vconflictlast_v_i32m2_b16(vs2, vl);
}

// CHECK-RV64-LABEL: @test_vconflictlast_v_i64m1_b64(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i1> @llvm.riscv.vconflictlast.nxv1i64.i64(<vscale x 1 x i1> poison, <vscale x 1 x i64> [[VS2:%.*]], i64 [[VL:%.*]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i1> [[TMP0]]
//
vbool64_t test_vconflictlast_v_i64m1_b64(vint64m1_t vs2, size_t vl) {
  return __riscv_vconflictlast_v_i64m1_b64(vs2, vl);
}

// CHECK-RV64-LABEL: @test_vconflictlast_v_u32m1_b32(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i1> @llvm.riscv.vconflictlast.nxv2i32.i64(<vscale x 2 x i1> poison, <vscale x 2 x i32> [[VS2:%.*]], i64 [[VL:%.*]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i1> [[TMP0]]
//
vbool32_t test_vconflictlast_v_u32m1_b32(vuint32m1_t vs2, size_t vl) {
  return __riscv_vconflictlast_v_u32m1_b32(vs2, vl);
}

// CHECK-RV64-LABEL: @test_vconflictlast_v_u64m2_b32(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i1> @llvm.riscv.vconflictlast.nxv2i64.i64(<vscale x 2 x i1> poison, <vscale x 2 x i64> [[VS2:%.*]], i64 [[VL:%.*]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i1> [[TMP0]]
//
vbool32_t test_vconflictlast_v_u64m2_b32(vuint64m2_t vs2, size_t vl) {
  return __riscv_vconflictlast_v_u64m2_b32(vs2, vl);
}

// CHECK-RV64-LABEL: @test_vconflictlast_v_i32m1_b32_m(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i1> @llvm.riscv.vconflictlast.mask.nxv2i32.i64(<vscale x 2 x i1> poison, <vscale x 2 x i32> [[VS2:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i1> [[TMP0]]
//
vbool32_t test_vconflictlast_v_i32m1_b32_m(vbool32_t mask, vint32m1_t vs2, size_t vl) {
  return __riscv_vconflictlast_v_i32m1_b32_m(mask, vs2, vl);
}

// CHECK-RV64-LABEL: @test_vconflictlast_v_u64m2_b32_m(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i1> @llvm.riscv.vconflictlast.mask.nxv2i64.i64(<vscale x 2 x i1> poison, <vscale x 2 x i64> [[VS2:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i1> [[TMP0]]
//
vbool32_t test_vconflictlast_v_u64m2_b32_m(vbool32_t mask, vuint64m2_t vs2, size_t vl) {
  return __riscv_vconflictlast_v_u64m2_b32_m(mask, vs2, vl);
}
