// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv64 -target-feature +v \
// RUN:   -target-feature +experimental-zvcd -disable-O0-optnone \
// RUN:   -emit-llvm %s -o - | opt -S -passes=mem2reg | \
// RUN:   FileCheck --check-prefix=CHECK-RV64 %s

#include <riscv_vector.h>

// CHECK-RV64-LABEL: @test_vconflictlast_v_i32m1_b32_tu(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i1> @llvm.riscv.vconflictlast.nxv2i32.i64(<vscale x 2 x i1> [[MASKEDOFF:%.*]], <vscale x 2 x i32> [[VS2:%.*]], i64 [[VL:%.*]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i1> [[TMP0]]
//
vbool32_t test_vconflictlast_v_i32m1_b32_tu(vbool32_t maskedoff, vint32m1_t vs2, size_t vl) {
  return __riscv_vconflictlast_v_i32m1_b32_tu(maskedoff, vs2, vl);
}

// CHECK-RV64-LABEL: @test_vconflictlast_v_i32m1_b32_mu(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i1> @llvm.riscv.vconflictlast.mask.nxv2i32.i64(<vscale x 2 x i1> [[MASKEDOFF:%.*]], <vscale x 2 x i32> [[VS2:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i1> [[TMP0]]
//
vbool32_t test_vconflictlast_v_i32m1_b32_mu(vbool32_t mask, vbool32_t maskedoff, vint32m1_t vs2, size_t vl) {
  return __riscv_vconflictlast_v_i32m1_b32_mu(mask, maskedoff, vs2, vl);
}

// CHECK-RV64-LABEL: @test_vconflictlast_v_u64m2_b32_mu(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i1> @llvm.riscv.vconflictlast.mask.nxv2i64.i64(<vscale x 2 x i1> [[MASKEDOFF:%.*]], <vscale x 2 x i64> [[VS2:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i1> [[TMP0]]
//
vbool32_t test_vconflictlast_v_u64m2_b32_mu(vbool32_t mask, vbool32_t maskedoff, vuint64m2_t vs2, size_t vl) {
  return __riscv_vconflictlast_v_u64m2_b32_mu(mask, maskedoff, vs2, vl);
}
