// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv64 -target-feature +v \
// RUN:   -target-feature +experimental-zvcd -disable-O0-optnone \
// RUN:   -emit-llvm %s -o - | opt -S -passes=mem2reg | \
// RUN:   FileCheck --check-prefix=CHECK-RV64 %s

#include <riscv_vector.h>

// CHECK-RV64-LABEL: @test_vconflictcnt_v_i32m1_tu(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vconflictcnt.nxv2i32.i64(<vscale x 2 x i32> [[VD:%.*]], <vscale x 2 x i32> [[VS2:%.*]], i64 [[VL:%.*]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vconflictcnt_v_i32m1_tu(vint32m1_t vd, vint32m1_t vs2, size_t vl) {
  return __riscv_vconflictcnt_v_i32m1_tu(vd, vs2, vl);
}

// CHECK-RV64-LABEL: @test_vconflictcnt_v_u64m2_tu(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vconflictcnt.nxv2i64.i64(<vscale x 2 x i64> [[VD:%.*]], <vscale x 2 x i64> [[VS2:%.*]], i64 [[VL:%.*]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vuint64m2_t test_vconflictcnt_v_u64m2_tu(vuint64m2_t vd, vuint64m2_t vs2, size_t vl) {
  return __riscv_vconflictcnt_v_u64m2_tu(vd, vs2, vl);
}

// CHECK-RV64-LABEL: @test_vconflictcnt_v_i32m1_tum(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vconflictcnt.mask.nxv2i32.i64(<vscale x 2 x i32> [[VD:%.*]], <vscale x 2 x i32> [[VS2:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 2)
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vconflictcnt_v_i32m1_tum(vbool32_t mask, vint32m1_t vd, vint32m1_t vs2, size_t vl) {
  return __riscv_vconflictcnt_v_i32m1_tum(mask, vd, vs2, vl);
}

// CHECK-RV64-LABEL: @test_vconflictcnt_v_i32m1_tumu(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vconflictcnt.mask.nxv2i32.i64(<vscale x 2 x i32> [[VD:%.*]], <vscale x 2 x i32> [[VS2:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0)
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vconflictcnt_v_i32m1_tumu(vbool32_t mask, vint32m1_t vd, vint32m1_t vs2, size_t vl) {
  return __riscv_vconflictcnt_v_i32m1_tumu(mask, vd, vs2, vl);
}

// CHECK-RV64-LABEL: @test_vconflictcnt_v_u64m2_mu(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vconflictcnt.mask.nxv2i64.i64(<vscale x 2 x i64> [[VD:%.*]], <vscale x 2 x i64> [[VS2:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 1)
// CHECK-RV64-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vuint64m2_t test_vconflictcnt_v_u64m2_mu(vbool32_t mask, vuint64m2_t vd, vuint64m2_t vs2, size_t vl) {
  return __riscv_vconflictcnt_v_u64m2_mu(mask, vd, vs2, vl);
}
