; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefixes=CHECK,RV64I
; RUN: llc -mtriple=riscv64 -mattr=+xtheadbext -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefixes=CHECK,RV64XTHEADBEXT

define signext i32 @sexti1_i32(i32 signext %a) nounwind {
; RV64I-LABEL: sexti1_i32:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 63
; RV64I-NEXT:    srai a0, a0, 63
; RV64I-NEXT:    ret
;
; RV64XTHEADBEXT-LABEL: sexti1_i32:
; RV64XTHEADBEXT:       # %bb.0:
; RV64XTHEADBEXT-NEXT:    th.ext a0, a0, 0, 0
; RV64XTHEADBEXT-NEXT:    ret
  %shl = shl i32 %a, 31
  %shr = ashr exact i32 %shl, 31
  ret i32 %shr
}

define signext i32 @sexti1_i32_2(i1 %a) nounwind {
; RV64I-LABEL: sexti1_i32_2:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 63
; RV64I-NEXT:    srai a0, a0, 63
; RV64I-NEXT:    ret
;
; RV64XTHEADBEXT-LABEL: sexti1_i32_2:
; RV64XTHEADBEXT:       # %bb.0:
; RV64XTHEADBEXT-NEXT:    th.ext a0, a0, 0, 0
; RV64XTHEADBEXT-NEXT:    ret
  %sext = sext i1 %a to i32
  ret i32 %sext
}

define i64 @sexti1_i64(i64 %a) nounwind {
; RV64I-LABEL: sexti1_i64:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 63
; RV64I-NEXT:    srai a0, a0, 63
; RV64I-NEXT:    ret
;
; RV64XTHEADBEXT-LABEL: sexti1_i64:
; RV64XTHEADBEXT:       # %bb.0:
; RV64XTHEADBEXT-NEXT:    th.ext a0, a0, 0, 0
; RV64XTHEADBEXT-NEXT:    ret
  %shl = shl i64 %a, 63
  %shr = ashr exact i64 %shl, 63
  ret i64 %shr
}

define i64 @sexti1_i64_2(i1 %a) nounwind {
; RV64I-LABEL: sexti1_i64_2:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 63
; RV64I-NEXT:    srai a0, a0, 63
; RV64I-NEXT:    ret
;
; RV64XTHEADBEXT-LABEL: sexti1_i64_2:
; RV64XTHEADBEXT:       # %bb.0:
; RV64XTHEADBEXT-NEXT:    th.ext a0, a0, 0, 0
; RV64XTHEADBEXT-NEXT:    ret
  %sext = sext i1 %a to i64
  ret i64 %sext
}

define signext i32 @sextb_i32(i32 signext %a) nounwind {
; RV64I-LABEL: sextb_i32:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 56
; RV64I-NEXT:    srai a0, a0, 56
; RV64I-NEXT:    ret
;
; RV64XTHEADBEXT-LABEL: sextb_i32:
; RV64XTHEADBEXT:       # %bb.0:
; RV64XTHEADBEXT-NEXT:    th.ext a0, a0, 7, 0
; RV64XTHEADBEXT-NEXT:    ret
  %shl = shl i32 %a, 24
  %shr = ashr exact i32 %shl, 24
  ret i32 %shr
}

define i64 @sextb_i64(i64 %a) nounwind {
; RV64I-LABEL: sextb_i64:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 56
; RV64I-NEXT:    srai a0, a0, 56
; RV64I-NEXT:    ret
;
; RV64XTHEADBEXT-LABEL: sextb_i64:
; RV64XTHEADBEXT:       # %bb.0:
; RV64XTHEADBEXT-NEXT:    th.ext a0, a0, 7, 0
; RV64XTHEADBEXT-NEXT:    ret
  %shl = shl i64 %a, 56
  %shr = ashr exact i64 %shl, 56
  ret i64 %shr
}

define signext i32 @sexth_i32(i32 signext %a) nounwind {
; RV64I-LABEL: sexth_i32:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 48
; RV64I-NEXT:    srai a0, a0, 48
; RV64I-NEXT:    ret
;
; RV64XTHEADBEXT-LABEL: sexth_i32:
; RV64XTHEADBEXT:       # %bb.0:
; RV64XTHEADBEXT-NEXT:    th.ext a0, a0, 15, 0
; RV64XTHEADBEXT-NEXT:    ret
  %shl = shl i32 %a, 16
  %shr = ashr exact i32 %shl, 16
  ret i32 %shr
}

define i64 @sexth_i64(i64 %a) nounwind {
; RV64I-LABEL: sexth_i64:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 48
; RV64I-NEXT:    srai a0, a0, 48
; RV64I-NEXT:    ret
;
; RV64XTHEADBEXT-LABEL: sexth_i64:
; RV64XTHEADBEXT:       # %bb.0:
; RV64XTHEADBEXT-NEXT:    th.ext a0, a0, 15, 0
; RV64XTHEADBEXT-NEXT:    ret
  %shl = shl i64 %a, 48
  %shr = ashr exact i64 %shl, 48
  ret i64 %shr
}

define i32 @zexth_i32(i32 %a) nounwind {
; RV64I-LABEL: zexth_i32:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 48
; RV64I-NEXT:    srli a0, a0, 48
; RV64I-NEXT:    ret
;
; RV64XTHEADBEXT-LABEL: zexth_i32:
; RV64XTHEADBEXT:       # %bb.0:
; RV64XTHEADBEXT-NEXT:    th.extu a0, a0, 15, 0
; RV64XTHEADBEXT-NEXT:    ret
  %and = and i32 %a, 65535
  ret i32 %and
}

define i64 @zexth_i64(i64 %a) nounwind {
; RV64I-LABEL: zexth_i64:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 48
; RV64I-NEXT:    srli a0, a0, 48
; RV64I-NEXT:    ret
;
; RV64XTHEADBEXT-LABEL: zexth_i64:
; RV64XTHEADBEXT:       # %bb.0:
; RV64XTHEADBEXT-NEXT:    th.extu a0, a0, 15, 0
; RV64XTHEADBEXT-NEXT:    ret
  %and = and i64 %a, 65535
  ret i64 %and
}

define i64 @zextw_i64(i64 %a) nounwind {
; RV64I-LABEL: zextw_i64:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 32
; RV64I-NEXT:    srli a0, a0, 32
; RV64I-NEXT:    ret
;
; RV64XTHEADBEXT-LABEL: zextw_i64:
; RV64XTHEADBEXT:       # %bb.0:
; RV64XTHEADBEXT-NEXT:    th.extu a0, a0, 31, 0
; RV64XTHEADBEXT-NEXT:    ret
  %and = and i64 %a, 4294967295
  ret i64 %and
}

define i64 @zext_bf_i64(i64 %a) nounwind {
; RV64I-LABEL: zext_bf_i64:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 47
; RV64I-NEXT:    srli a0, a0, 48
; RV64I-NEXT:    ret
;
; RV64XTHEADBEXT-LABEL: zext_bf_i64:
; RV64XTHEADBEXT:       # %bb.0:
; RV64XTHEADBEXT-NEXT:    th.extu a0, a0, 16, 1
; RV64XTHEADBEXT-NEXT:    ret
  %1 = lshr i64 %a, 1
  %and = and i64 %1, 65535
  ret i64 %and
}

define i64 @zext_bf2_i64(i64 %a) nounwind {
; RV64I-LABEL: zext_bf2_i64:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 48
; RV64I-NEXT:    srli a0, a0, 49
; RV64I-NEXT:    ret
;
; RV64XTHEADBEXT-LABEL: zext_bf2_i64:
; RV64XTHEADBEXT:       # %bb.0:
; RV64XTHEADBEXT-NEXT:    th.extu a0, a0, 15, 1
; RV64XTHEADBEXT-NEXT:    ret
  %t0 = and i64 %a, 65535
  %result = lshr i64 %t0, 1
  ret i64 %result
}
