; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+zfhmin,+f,+d -verify-machineinstrs < %s | FileCheck -check-prefix=RV32 %s
; RUN: llc -mtriple=riscv32 -mattr=+zfhmin,+f,+d,+zflx,+zfsx -verify-machineinstrs < %s | FileCheck -check-prefix=RV32-ZFLSX %s
; RUN: llc -mtriple=riscv64 -mattr=+zfhmin,+f,+d -verify-machineinstrs < %s | FileCheck -check-prefix=RV64 %s
; RUN: llc -mtriple=riscv64 -mattr=+zfhmin,+f,+d,+zflx,+zfsx -verify-machineinstrs < %s | FileCheck -check-prefix=RV64-ZFLSX %s

define half @flxh(ptr %a, i64 %b) {
; RV32-LABEL: flxh:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 1
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    flh fa5, 0(a0)
; RV32-NEXT:    fcvt.s.h fa5, fa5
; RV32-NEXT:    fadd.s fa5, fa5, fa5
; RV32-NEXT:    fcvt.h.s fa0, fa5
; RV32-NEXT:    ret
;
; RV32-ZFLSX-LABEL: flxh:
; RV32-ZFLSX:       # %bb.0:
; RV32-ZFLSX-NEXT:    slli a1, a1, 1
; RV32-ZFLSX-NEXT:    add a0, a0, a1
; RV32-ZFLSX-NEXT:    flh fa5, 0(a0)
; RV32-ZFLSX-NEXT:    fcvt.s.h fa5, fa5
; RV32-ZFLSX-NEXT:    fadd.s fa5, fa5, fa5
; RV32-ZFLSX-NEXT:    fcvt.h.s fa0, fa5
; RV32-ZFLSX-NEXT:    ret
;
; RV64-LABEL: flxh:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 1
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    flh fa5, 0(a0)
; RV64-NEXT:    fcvt.s.h fa5, fa5
; RV64-NEXT:    fadd.s fa5, fa5, fa5
; RV64-NEXT:    fcvt.h.s fa0, fa5
; RV64-NEXT:    ret
;
; RV64-ZFLSX-LABEL: flxh:
; RV64-ZFLSX:       # %bb.0:
; RV64-ZFLSX-NEXT:    slli a1, a1, 1
; RV64-ZFLSX-NEXT:    add a0, a0, a1
; RV64-ZFLSX-NEXT:    flh fa5, 0(a0)
; RV64-ZFLSX-NEXT:    fcvt.s.h fa5, fa5
; RV64-ZFLSX-NEXT:    fadd.s fa5, fa5, fa5
; RV64-ZFLSX-NEXT:    fcvt.h.s fa0, fa5
; RV64-ZFLSX-NEXT:    ret
  %1 = getelementptr half, ptr %a, i64 %b
  %2 = load half, ptr %1, align 4
  %3 = fadd half %2, %2
  ret half %3
}

define void @fsxh(ptr %a, i64 %b, half %c) {
; RV32-LABEL: fsxh:
; RV32:       # %bb.0:
; RV32-NEXT:    fcvt.s.h fa5, fa0
; RV32-NEXT:    slli a1, a1, 1
; RV32-NEXT:    fadd.s fa5, fa5, fa5
; RV32-NEXT:    fcvt.h.s fa5, fa5
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    fsh fa5, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZFLSX-LABEL: fsxh:
; RV32-ZFLSX:       # %bb.0:
; RV32-ZFLSX-NEXT:    fcvt.s.h fa5, fa0
; RV32-ZFLSX-NEXT:    slli a1, a1, 1
; RV32-ZFLSX-NEXT:    fadd.s fa5, fa5, fa5
; RV32-ZFLSX-NEXT:    fcvt.h.s fa5, fa5
; RV32-ZFLSX-NEXT:    add a0, a0, a1
; RV32-ZFLSX-NEXT:    fsh fa5, 0(a0)
; RV32-ZFLSX-NEXT:    ret
;
; RV64-LABEL: fsxh:
; RV64:       # %bb.0:
; RV64-NEXT:    fcvt.s.h fa5, fa0
; RV64-NEXT:    slli a1, a1, 1
; RV64-NEXT:    fadd.s fa5, fa5, fa5
; RV64-NEXT:    fcvt.h.s fa5, fa5
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    fsh fa5, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZFLSX-LABEL: fsxh:
; RV64-ZFLSX:       # %bb.0:
; RV64-ZFLSX-NEXT:    fcvt.s.h fa5, fa0
; RV64-ZFLSX-NEXT:    slli a1, a1, 1
; RV64-ZFLSX-NEXT:    fadd.s fa5, fa5, fa5
; RV64-ZFLSX-NEXT:    fcvt.h.s fa5, fa5
; RV64-ZFLSX-NEXT:    add a0, a0, a1
; RV64-ZFLSX-NEXT:    fsh fa5, 0(a0)
; RV64-ZFLSX-NEXT:    ret
  %1 = fadd half %c, %c
  %2 = getelementptr half, ptr %a, i64 %b
  store half %1, ptr %2, align 4
  ret void
}

define float @flxw(ptr %a, i64 %b) {
; RV32-LABEL: flxw:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 2
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    flw fa5, 0(a0)
; RV32-NEXT:    fadd.s fa0, fa5, fa5
; RV32-NEXT:    ret
;
; RV32-ZFLSX-LABEL: flxw:
; RV32-ZFLSX:       # %bb.0:
; RV32-ZFLSX-NEXT:    slli a1, a1, 2
; RV32-ZFLSX-NEXT:    add a0, a0, a1
; RV32-ZFLSX-NEXT:    flw fa5, 0(a0)
; RV32-ZFLSX-NEXT:    fadd.s fa0, fa5, fa5
; RV32-ZFLSX-NEXT:    ret
;
; RV64-LABEL: flxw:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 2
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    flw fa5, 0(a0)
; RV64-NEXT:    fadd.s fa0, fa5, fa5
; RV64-NEXT:    ret
;
; RV64-ZFLSX-LABEL: flxw:
; RV64-ZFLSX:       # %bb.0:
; RV64-ZFLSX-NEXT:    slli a1, a1, 2
; RV64-ZFLSX-NEXT:    add a0, a0, a1
; RV64-ZFLSX-NEXT:    flw fa5, 0(a0)
; RV64-ZFLSX-NEXT:    fadd.s fa0, fa5, fa5
; RV64-ZFLSX-NEXT:    ret
  %1 = getelementptr float, ptr %a, i64 %b
  %2 = load float, ptr %1, align 4
  %3 = fadd float %2, %2
  ret float %3
}

define void @fsxw(ptr %a, i64 %b, float %c) {
; RV32-LABEL: fsxw:
; RV32:       # %bb.0:
; RV32-NEXT:    fadd.s fa5, fa0, fa0
; RV32-NEXT:    slli a1, a1, 2
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    fsw fa5, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZFLSX-LABEL: fsxw:
; RV32-ZFLSX:       # %bb.0:
; RV32-ZFLSX-NEXT:    fadd.s fa5, fa0, fa0
; RV32-ZFLSX-NEXT:    slli a1, a1, 2
; RV32-ZFLSX-NEXT:    add a0, a0, a1
; RV32-ZFLSX-NEXT:    fsw fa5, 0(a0)
; RV32-ZFLSX-NEXT:    ret
;
; RV64-LABEL: fsxw:
; RV64:       # %bb.0:
; RV64-NEXT:    fadd.s fa5, fa0, fa0
; RV64-NEXT:    slli a1, a1, 2
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    fsw fa5, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZFLSX-LABEL: fsxw:
; RV64-ZFLSX:       # %bb.0:
; RV64-ZFLSX-NEXT:    fadd.s fa5, fa0, fa0
; RV64-ZFLSX-NEXT:    slli a1, a1, 2
; RV64-ZFLSX-NEXT:    add a0, a0, a1
; RV64-ZFLSX-NEXT:    fsw fa5, 0(a0)
; RV64-ZFLSX-NEXT:    ret
  %1 = fadd float %c, %c
  %2 = getelementptr float, ptr %a, i64 %b
  store float %1, ptr %2, align 4
  ret void
}

define double @flxd(ptr %a, i64 %b) {
; RV32-LABEL: flxd:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 3
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    fld fa5, 0(a0)
; RV32-NEXT:    fadd.d fa0, fa5, fa5
; RV32-NEXT:    ret
;
; RV32-ZFLSX-LABEL: flxd:
; RV32-ZFLSX:       # %bb.0:
; RV32-ZFLSX-NEXT:    slli a1, a1, 3
; RV32-ZFLSX-NEXT:    add a0, a0, a1
; RV32-ZFLSX-NEXT:    fld fa5, 0(a0)
; RV32-ZFLSX-NEXT:    fadd.d fa0, fa5, fa5
; RV32-ZFLSX-NEXT:    ret
;
; RV64-LABEL: flxd:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 3
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    fld fa5, 0(a0)
; RV64-NEXT:    fadd.d fa0, fa5, fa5
; RV64-NEXT:    ret
;
; RV64-ZFLSX-LABEL: flxd:
; RV64-ZFLSX:       # %bb.0:
; RV64-ZFLSX-NEXT:    slli a1, a1, 3
; RV64-ZFLSX-NEXT:    add a0, a0, a1
; RV64-ZFLSX-NEXT:    fld fa5, 0(a0)
; RV64-ZFLSX-NEXT:    fadd.d fa0, fa5, fa5
; RV64-ZFLSX-NEXT:    ret
  %1 = getelementptr double, ptr %a, i64 %b
  %2 = load double, ptr %1, align 8
  %3 = fadd double %2, %2
  ret double %3
}

define void @fsxd(ptr %a, i64 %b, double %c) {
; RV32-LABEL: fsxd:
; RV32:       # %bb.0:
; RV32-NEXT:    fadd.d fa5, fa0, fa0
; RV32-NEXT:    slli a1, a1, 3
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    fsd fa5, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZFLSX-LABEL: fsxd:
; RV32-ZFLSX:       # %bb.0:
; RV32-ZFLSX-NEXT:    fadd.d fa5, fa0, fa0
; RV32-ZFLSX-NEXT:    slli a1, a1, 3
; RV32-ZFLSX-NEXT:    add a0, a0, a1
; RV32-ZFLSX-NEXT:    fsd fa5, 0(a0)
; RV32-ZFLSX-NEXT:    ret
;
; RV64-LABEL: fsxd:
; RV64:       # %bb.0:
; RV64-NEXT:    fadd.d fa5, fa0, fa0
; RV64-NEXT:    slli a1, a1, 3
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    fsd fa5, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZFLSX-LABEL: fsxd:
; RV64-ZFLSX:       # %bb.0:
; RV64-ZFLSX-NEXT:    fadd.d fa5, fa0, fa0
; RV64-ZFLSX-NEXT:    slli a1, a1, 3
; RV64-ZFLSX-NEXT:    add a0, a0, a1
; RV64-ZFLSX-NEXT:    fsd fa5, 0(a0)
; RV64-ZFLSX-NEXT:    ret
  %1 = fadd double %c, %c
  %2 = getelementptr double, ptr %a, i64 %b
  store double %1, ptr %2, align 8
  ret void
}
