; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -verify-machineinstrs < %s | FileCheck -check-prefix=RV32 %s
; RUN: llc -mtriple=riscv32 -mattr=+zilsx -verify-machineinstrs < %s | FileCheck -check-prefix=RV32-ZILSX %s
; RUN: llc -mtriple=riscv64 -verify-machineinstrs < %s | FileCheck -check-prefix=RV64 %s
; RUN: llc -mtriple=riscv64 -mattr=+zilsx -verify-machineinstrs < %s | FileCheck -check-prefix=RV64-ZILSX %s

define i8 @lxb_anyext(ptr %a, i64 %b) {
; RV32-LABEL: lxb_anyext:
; RV32:       # %bb.0:
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lbu a0, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZILSX-LABEL: lxb_anyext:
; RV32-ZILSX:       # %bb.0:
; RV32-ZILSX-NEXT:    lxb a0, (a0), a1
; RV32-ZILSX-NEXT:    ret
;
; RV64-LABEL: lxb_anyext:
; RV64:       # %bb.0:
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lbu a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILSX-LABEL: lxb_anyext:
; RV64-ZILSX:       # %bb.0:
; RV64-ZILSX-NEXT:    lxb a0, (a0), a1
; RV64-ZILSX-NEXT:    ret
  %1 = getelementptr i8, ptr %a, i64 %b
  %2 = load i8, ptr %1, align 1
  ret i8 %2
}

define i64 @lxb(ptr %a, i64 %b) {
; RV32-LABEL: lxb:
; RV32:       # %bb.0:
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lb a1, 0(a0)
; RV32-NEXT:    srai a2, a1, 31
; RV32-NEXT:    add a0, a1, a1
; RV32-NEXT:    sltu a1, a0, a1
; RV32-NEXT:    add a2, a2, a2
; RV32-NEXT:    add a1, a2, a1
; RV32-NEXT:    ret
;
; RV32-ZILSX-LABEL: lxb:
; RV32-ZILSX:       # %bb.0:
; RV32-ZILSX-NEXT:    lxb a1, (a0), a1
; RV32-ZILSX-NEXT:    srai a2, a1, 31
; RV32-ZILSX-NEXT:    add a0, a1, a1
; RV32-ZILSX-NEXT:    sltu a1, a0, a1
; RV32-ZILSX-NEXT:    add a2, a2, a2
; RV32-ZILSX-NEXT:    add a1, a2, a1
; RV32-ZILSX-NEXT:    ret
;
; RV64-LABEL: lxb:
; RV64:       # %bb.0:
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lb a0, 0(a0)
; RV64-NEXT:    add a0, a0, a0
; RV64-NEXT:    ret
;
; RV64-ZILSX-LABEL: lxb:
; RV64-ZILSX:       # %bb.0:
; RV64-ZILSX-NEXT:    lxb a0, (a0), a1
; RV64-ZILSX-NEXT:    add a0, a0, a0
; RV64-ZILSX-NEXT:    ret
  %1 = getelementptr i8, ptr %a, i64 %b
  %2 = load i8, ptr %1, align 1
  %3 = sext i8 %2 to i64
  %4 = add i64 %3, %3
  ret i64 %4
}

define i64 @lxbu(ptr %a, i64 %b) {
; RV32-LABEL: lxbu:
; RV32:       # %bb.0:
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lbu a1, 0(a0)
; RV32-NEXT:    add a0, a1, a1
; RV32-NEXT:    sltu a1, a0, a1
; RV32-NEXT:    ret
;
; RV32-ZILSX-LABEL: lxbu:
; RV32-ZILSX:       # %bb.0:
; RV32-ZILSX-NEXT:    lxbu a1, (a0), a1
; RV32-ZILSX-NEXT:    add a0, a1, a1
; RV32-ZILSX-NEXT:    sltu a1, a0, a1
; RV32-ZILSX-NEXT:    ret
;
; RV64-LABEL: lxbu:
; RV64:       # %bb.0:
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lbu a0, 0(a0)
; RV64-NEXT:    add a0, a0, a0
; RV64-NEXT:    ret
;
; RV64-ZILSX-LABEL: lxbu:
; RV64-ZILSX:       # %bb.0:
; RV64-ZILSX-NEXT:    lxbu a0, (a0), a1
; RV64-ZILSX-NEXT:    add a0, a0, a0
; RV64-ZILSX-NEXT:    ret
  %1 = getelementptr i8, ptr %a, i64 %b
  %2 = load i8, ptr %1, align 1
  %3 = zext i8 %2 to i64
  %4 = add i64 %3, %3
  ret i64 %4
}

define i16 @lxh_anyext(ptr %a, i64 %b) {
; RV32-LABEL: lxh_anyext:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 1
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lh a0, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZILSX-LABEL: lxh_anyext:
; RV32-ZILSX:       # %bb.0:
; RV32-ZILSX-NEXT:    lxh a0, (a0), a1, 1
; RV32-ZILSX-NEXT:    ret
;
; RV64-LABEL: lxh_anyext:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 1
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lh a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILSX-LABEL: lxh_anyext:
; RV64-ZILSX:       # %bb.0:
; RV64-ZILSX-NEXT:    lxh a0, (a0), a1, 1
; RV64-ZILSX-NEXT:    ret
  %1 = getelementptr i16, ptr %a, i64 %b
  %2 = load i16, ptr %1, align 2
  ret i16 %2
}

define i64 @lxh(ptr %a, i64 %b) {
; RV32-LABEL: lxh:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 1
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lh a1, 0(a0)
; RV32-NEXT:    srai a2, a1, 31
; RV32-NEXT:    add a0, a1, a1
; RV32-NEXT:    sltu a1, a0, a1
; RV32-NEXT:    add a2, a2, a2
; RV32-NEXT:    add a1, a2, a1
; RV32-NEXT:    ret
;
; RV32-ZILSX-LABEL: lxh:
; RV32-ZILSX:       # %bb.0:
; RV32-ZILSX-NEXT:    lxh a1, (a0), a1, 1
; RV32-ZILSX-NEXT:    srai a2, a1, 31
; RV32-ZILSX-NEXT:    add a0, a1, a1
; RV32-ZILSX-NEXT:    sltu a1, a0, a1
; RV32-ZILSX-NEXT:    add a2, a2, a2
; RV32-ZILSX-NEXT:    add a1, a2, a1
; RV32-ZILSX-NEXT:    ret
;
; RV64-LABEL: lxh:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 1
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lh a0, 0(a0)
; RV64-NEXT:    add a0, a0, a0
; RV64-NEXT:    ret
;
; RV64-ZILSX-LABEL: lxh:
; RV64-ZILSX:       # %bb.0:
; RV64-ZILSX-NEXT:    lxh a0, (a0), a1, 1
; RV64-ZILSX-NEXT:    add a0, a0, a0
; RV64-ZILSX-NEXT:    ret
  %1 = getelementptr i16, ptr %a, i64 %b
  %2 = load i16, ptr %1, align 2
  %3 = sext i16 %2 to i64
  %4 = add i64 %3, %3
  ret i64 %4
}

define i64 @lxhu(ptr %a, i64 %b) {
; RV32-LABEL: lxhu:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 1
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lhu a1, 0(a0)
; RV32-NEXT:    add a0, a1, a1
; RV32-NEXT:    sltu a1, a0, a1
; RV32-NEXT:    ret
;
; RV32-ZILSX-LABEL: lxhu:
; RV32-ZILSX:       # %bb.0:
; RV32-ZILSX-NEXT:    lxhu a1, (a0), a1, 1
; RV32-ZILSX-NEXT:    add a0, a1, a1
; RV32-ZILSX-NEXT:    sltu a1, a0, a1
; RV32-ZILSX-NEXT:    ret
;
; RV64-LABEL: lxhu:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 1
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lhu a0, 0(a0)
; RV64-NEXT:    add a0, a0, a0
; RV64-NEXT:    ret
;
; RV64-ZILSX-LABEL: lxhu:
; RV64-ZILSX:       # %bb.0:
; RV64-ZILSX-NEXT:    lxhu a0, (a0), a1, 1
; RV64-ZILSX-NEXT:    add a0, a0, a0
; RV64-ZILSX-NEXT:    ret
  %1 = getelementptr i16, ptr %a, i64 %b
  %2 = load i16, ptr %1, align 2
  %3 = zext i16 %2 to i64
  %4 = add i64 %3, %3
  ret i64 %4
}

define i32 @lxw_anyext(ptr %a, i64 %b) {
; RV32-LABEL: lxw_anyext:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 2
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lw a0, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZILSX-LABEL: lxw_anyext:
; RV32-ZILSX:       # %bb.0:
; RV32-ZILSX-NEXT:    lxw a0, (a0), a1, 2
; RV32-ZILSX-NEXT:    ret
;
; RV64-LABEL: lxw_anyext:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 2
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lw a0, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILSX-LABEL: lxw_anyext:
; RV64-ZILSX:       # %bb.0:
; RV64-ZILSX-NEXT:    lxw a0, (a0), a1, 2
; RV64-ZILSX-NEXT:    ret
  %1 = getelementptr i32, ptr %a, i64 %b
  %2 = load i32, ptr %1, align 4
  ret i32 %2
}

define i64 @lxw(ptr %a, i64 %b) {
; RV32-LABEL: lxw:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 2
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lw a1, 0(a0)
; RV32-NEXT:    srai a2, a1, 31
; RV32-NEXT:    add a0, a1, a1
; RV32-NEXT:    sltu a1, a0, a1
; RV32-NEXT:    add a2, a2, a2
; RV32-NEXT:    add a1, a2, a1
; RV32-NEXT:    ret
;
; RV32-ZILSX-LABEL: lxw:
; RV32-ZILSX:       # %bb.0:
; RV32-ZILSX-NEXT:    lxw a1, (a0), a1, 2
; RV32-ZILSX-NEXT:    srai a2, a1, 31
; RV32-ZILSX-NEXT:    add a0, a1, a1
; RV32-ZILSX-NEXT:    sltu a1, a0, a1
; RV32-ZILSX-NEXT:    add a2, a2, a2
; RV32-ZILSX-NEXT:    add a1, a2, a1
; RV32-ZILSX-NEXT:    ret
;
; RV64-LABEL: lxw:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 2
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lw a0, 0(a0)
; RV64-NEXT:    add a0, a0, a0
; RV64-NEXT:    ret
;
; RV64-ZILSX-LABEL: lxw:
; RV64-ZILSX:       # %bb.0:
; RV64-ZILSX-NEXT:    lxw a0, (a0), a1, 2
; RV64-ZILSX-NEXT:    add a0, a0, a0
; RV64-ZILSX-NEXT:    ret
  %1 = getelementptr i32, ptr %a, i64 %b
  %2 = load i32, ptr %1, align 4
  %3 = sext i32 %2 to i64
  %4 = add i64 %3, %3
  ret i64 %4
}

define i64 @lxwu(ptr %a, i64 %b) {
; RV32-LABEL: lxwu:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 2
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lw a1, 0(a0)
; RV32-NEXT:    add a0, a1, a1
; RV32-NEXT:    sltu a1, a0, a1
; RV32-NEXT:    ret
;
; RV32-ZILSX-LABEL: lxwu:
; RV32-ZILSX:       # %bb.0:
; RV32-ZILSX-NEXT:    lxw a1, (a0), a1, 2
; RV32-ZILSX-NEXT:    add a0, a1, a1
; RV32-ZILSX-NEXT:    sltu a1, a0, a1
; RV32-ZILSX-NEXT:    ret
;
; RV64-LABEL: lxwu:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 2
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    lwu a0, 0(a0)
; RV64-NEXT:    add a0, a0, a0
; RV64-NEXT:    ret
;
; RV64-ZILSX-LABEL: lxwu:
; RV64-ZILSX:       # %bb.0:
; RV64-ZILSX-NEXT:    lxwu a0, (a0), a1, 2
; RV64-ZILSX-NEXT:    add a0, a0, a0
; RV64-ZILSX-NEXT:    ret
  %1 = getelementptr i32, ptr %a, i64 %b
  %2 = load i32, ptr %1, align 4
  %3 = zext i32 %2 to i64
  %4 = add i64 %3, %3
  ret i64 %4
}

define i64 @lxd(ptr %a, i64 %b) {
; RV32-LABEL: lxd:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 3
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    lw a1, 0(a0)
; RV32-NEXT:    lw a2, 4(a0)
; RV32-NEXT:    add a0, a1, a1
; RV32-NEXT:    sltu a1, a0, a1
; RV32-NEXT:    add a2, a2, a2
; RV32-NEXT:    add a1, a2, a1
; RV32-NEXT:    ret
;
; RV32-ZILSX-LABEL: lxd:
; RV32-ZILSX:       # %bb.0:
; RV32-ZILSX-NEXT:    slli a2, a1, 3
; RV32-ZILSX-NEXT:    lxw a1, (a0), a1, 3
; RV32-ZILSX-NEXT:    add a0, a0, a2
; RV32-ZILSX-NEXT:    lw a2, 4(a0)
; RV32-ZILSX-NEXT:    add a0, a1, a1
; RV32-ZILSX-NEXT:    sltu a1, a0, a1
; RV32-ZILSX-NEXT:    add a2, a2, a2
; RV32-ZILSX-NEXT:    add a1, a2, a1
; RV32-ZILSX-NEXT:    ret
;
; RV64-LABEL: lxd:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 3
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    ld a0, 0(a0)
; RV64-NEXT:    add a0, a0, a0
; RV64-NEXT:    ret
;
; RV64-ZILSX-LABEL: lxd:
; RV64-ZILSX:       # %bb.0:
; RV64-ZILSX-NEXT:    lxd a0, (a0), a1, 3
; RV64-ZILSX-NEXT:    add a0, a0, a0
; RV64-ZILSX-NEXT:    ret
  %1 = getelementptr i64, ptr %a, i64 %b
  %2 = load i64, ptr %1, align 8
  %3 = add i64 %2, %2
  ret i64 %3
}

define i64 @lxd_2(ptr %a, i64 %b) {
; RV32-LABEL: lxd_2:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 3
; RV32-NEXT:    add a0, a1, a0
; RV32-NEXT:    lw a1, 96(a0)
; RV32-NEXT:    lw a2, 100(a0)
; RV32-NEXT:    add a0, a1, a1
; RV32-NEXT:    sltu a1, a0, a1
; RV32-NEXT:    add a2, a2, a2
; RV32-NEXT:    add a1, a2, a1
; RV32-NEXT:    ret
;
; RV32-ZILSX-LABEL: lxd_2:
; RV32-ZILSX:       # %bb.0:
; RV32-ZILSX-NEXT:    addi a2, a0, 96
; RV32-ZILSX-NEXT:    lxw a2, (a2), a1, 3
; RV32-ZILSX-NEXT:    addi a0, a0, 100
; RV32-ZILSX-NEXT:    lxw a1, (a0), a1, 3
; RV32-ZILSX-NEXT:    add a0, a2, a2
; RV32-ZILSX-NEXT:    sltu a2, a0, a2
; RV32-ZILSX-NEXT:    add a1, a1, a1
; RV32-ZILSX-NEXT:    add a1, a1, a2
; RV32-ZILSX-NEXT:    ret
;
; RV64-LABEL: lxd_2:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 3
; RV64-NEXT:    add a0, a1, a0
; RV64-NEXT:    ld a0, 96(a0)
; RV64-NEXT:    add a0, a0, a0
; RV64-NEXT:    ret
;
; RV64-ZILSX-LABEL: lxd_2:
; RV64-ZILSX:       # %bb.0:
; RV64-ZILSX-NEXT:    addi a0, a0, 96
; RV64-ZILSX-NEXT:    lxd a0, (a0), a1, 3
; RV64-ZILSX-NEXT:    add a0, a0, a0
; RV64-ZILSX-NEXT:    ret
  %1 = add i64 %b, 12
  %2 = getelementptr i64, ptr %a, i64 %1
  %3 = load i64, ptr %2, align 8
  %4 = add i64 %3, %3
  ret i64 %4
}

define void @sxb(ptr %a, i64 %b, i8 %c) {
; RV32-LABEL: sxb:
; RV32:       # %bb.0:
; RV32-NEXT:    add a3, a3, a3
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    sb a3, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZILSX-LABEL: sxb:
; RV32-ZILSX:       # %bb.0:
; RV32-ZILSX-NEXT:    add a3, a3, a3
; RV32-ZILSX-NEXT:    sxb a3, (a0), a1
; RV32-ZILSX-NEXT:    ret
;
; RV64-LABEL: sxb:
; RV64:       # %bb.0:
; RV64-NEXT:    add a2, a2, a2
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    sb a2, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILSX-LABEL: sxb:
; RV64-ZILSX:       # %bb.0:
; RV64-ZILSX-NEXT:    add a2, a2, a2
; RV64-ZILSX-NEXT:    sxb a2, (a0), a1
; RV64-ZILSX-NEXT:    ret
  %1 = add i8 %c, %c
  %2 = getelementptr i8, ptr %a, i64 %b
  store i8 %1, ptr %2, align 1
  ret void
}

define void @sxh(ptr %a, i64 %b, i16 %c) {
; RV32-LABEL: sxh:
; RV32:       # %bb.0:
; RV32-NEXT:    add a3, a3, a3
; RV32-NEXT:    slli a1, a1, 1
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    sh a3, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZILSX-LABEL: sxh:
; RV32-ZILSX:       # %bb.0:
; RV32-ZILSX-NEXT:    add a3, a3, a3
; RV32-ZILSX-NEXT:    sxh a3, (a0), a1, 1
; RV32-ZILSX-NEXT:    ret
;
; RV64-LABEL: sxh:
; RV64:       # %bb.0:
; RV64-NEXT:    add a2, a2, a2
; RV64-NEXT:    slli a1, a1, 1
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    sh a2, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILSX-LABEL: sxh:
; RV64-ZILSX:       # %bb.0:
; RV64-ZILSX-NEXT:    add a2, a2, a2
; RV64-ZILSX-NEXT:    sxh a2, (a0), a1, 1
; RV64-ZILSX-NEXT:    ret
  %1 = add i16 %c, %c
  %2 = getelementptr i16, ptr %a, i64 %b
  store i16 %1, ptr %2, align 2
  ret void
}

define void @sxw(ptr %a, i64 %b, i32 %c) {
; RV32-LABEL: sxw:
; RV32:       # %bb.0:
; RV32-NEXT:    add a3, a3, a3
; RV32-NEXT:    slli a1, a1, 2
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    sw a3, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZILSX-LABEL: sxw:
; RV32-ZILSX:       # %bb.0:
; RV32-ZILSX-NEXT:    add a3, a3, a3
; RV32-ZILSX-NEXT:    sxw a3, (a0), a1, 2
; RV32-ZILSX-NEXT:    ret
;
; RV64-LABEL: sxw:
; RV64:       # %bb.0:
; RV64-NEXT:    add a2, a2, a2
; RV64-NEXT:    slli a1, a1, 2
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    sw a2, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILSX-LABEL: sxw:
; RV64-ZILSX:       # %bb.0:
; RV64-ZILSX-NEXT:    add a2, a2, a2
; RV64-ZILSX-NEXT:    sxw a2, (a0), a1, 2
; RV64-ZILSX-NEXT:    ret
  %1 = add i32 %c, %c
  %2 = getelementptr i32, ptr %a, i64 %b
  store i32 %1, ptr %2, align 4
  ret void
}

define void @sxd(ptr %a, i64 %b, i64 %c) {
; RV32-LABEL: sxd:
; RV32:       # %bb.0:
; RV32-NEXT:    add a2, a3, a3
; RV32-NEXT:    sltu a3, a2, a3
; RV32-NEXT:    add a4, a4, a4
; RV32-NEXT:    add a3, a4, a3
; RV32-NEXT:    slli a1, a1, 3
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    sw a2, 0(a0)
; RV32-NEXT:    sw a3, 4(a0)
; RV32-NEXT:    ret
;
; RV32-ZILSX-LABEL: sxd:
; RV32-ZILSX:       # %bb.0:
; RV32-ZILSX-NEXT:    add a2, a3, a3
; RV32-ZILSX-NEXT:    sltu a3, a2, a3
; RV32-ZILSX-NEXT:    add a4, a4, a4
; RV32-ZILSX-NEXT:    add a3, a4, a3
; RV32-ZILSX-NEXT:    slli a4, a1, 3
; RV32-ZILSX-NEXT:    add a4, a0, a4
; RV32-ZILSX-NEXT:    sxw a2, (a0), a1, 3
; RV32-ZILSX-NEXT:    sw a3, 4(a4)
; RV32-ZILSX-NEXT:    ret
;
; RV64-LABEL: sxd:
; RV64:       # %bb.0:
; RV64-NEXT:    add a2, a2, a2
; RV64-NEXT:    slli a1, a1, 3
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    sd a2, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZILSX-LABEL: sxd:
; RV64-ZILSX:       # %bb.0:
; RV64-ZILSX-NEXT:    add a2, a2, a2
; RV64-ZILSX-NEXT:    sxd a2, (a0), a1, 3
; RV64-ZILSX-NEXT:    ret
  %1 = add i64 %c, %c
  %2 = getelementptr i64, ptr %a, i64 %b
  store i64 %1, ptr %2, align 8
  ret void
}

define ptr @test_simm5(ptr %base, i32 %a, i32 %b) {
; RV32-LABEL: test_simm5:
; RV32:       # %bb.0:
; RV32-NEXT:    addi a3, a0, -48
; RV32-NEXT:    add a1, a1, a2
; RV32-NEXT:    sw a1, 0(a0)
; RV32-NEXT:    mv a0, a3
; RV32-NEXT:    ret
;
; RV32-ZILSX-LABEL: test_simm5:
; RV32-ZILSX:       # %bb.0:
; RV32-ZILSX-NEXT:    addi a3, a0, -48
; RV32-ZILSX-NEXT:    add a1, a1, a2
; RV32-ZILSX-NEXT:    sw a1, 0(a0)
; RV32-ZILSX-NEXT:    mv a0, a3
; RV32-ZILSX-NEXT:    ret
;
; RV64-LABEL: test_simm5:
; RV64:       # %bb.0:
; RV64-NEXT:    addi a3, a0, -48
; RV64-NEXT:    add a1, a1, a2
; RV64-NEXT:    sw a1, 0(a0)
; RV64-NEXT:    mv a0, a3
; RV64-NEXT:    ret
;
; RV64-ZILSX-LABEL: test_simm5:
; RV64-ZILSX:       # %bb.0:
; RV64-ZILSX-NEXT:    addi a3, a0, -48
; RV64-ZILSX-NEXT:    add a1, a1, a2
; RV64-ZILSX-NEXT:    sw a1, 0(a0)
; RV64-ZILSX-NEXT:    mv a0, a3
; RV64-ZILSX-NEXT:    ret
  %addr.1 = getelementptr i32, ptr %base, i32 -12
  %res = add i32 %a, %b
  store i32 %res, ptr %base
  ret ptr %addr.1
}

define i64 @lxd_large_shift(ptr %a, i64 %b) {
; RV32-LABEL: lxd_large_shift:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 5
; RV32-NEXT:    add a1, a1, a0
; RV32-NEXT:    lw a0, 384(a1)
; RV32-NEXT:    lw a1, 388(a1)
; RV32-NEXT:    ret
;
; RV32-ZILSX-LABEL: lxd_large_shift:
; RV32-ZILSX:       # %bb.0:
; RV32-ZILSX-NEXT:    slli a1, a1, 5
; RV32-ZILSX-NEXT:    add a1, a1, a0
; RV32-ZILSX-NEXT:    lw a0, 384(a1)
; RV32-ZILSX-NEXT:    lw a1, 388(a1)
; RV32-ZILSX-NEXT:    ret
;
; RV64-LABEL: lxd_large_shift:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 5
; RV64-NEXT:    add a0, a1, a0
; RV64-NEXT:    ld a0, 384(a0)
; RV64-NEXT:    ret
;
; RV64-ZILSX-LABEL: lxd_large_shift:
; RV64-ZILSX:       # %bb.0:
; RV64-ZILSX-NEXT:    slli a1, a1, 5
; RV64-ZILSX-NEXT:    add a0, a1, a0
; RV64-ZILSX-NEXT:    ld a0, 384(a0)
; RV64-ZILSX-NEXT:    ret
  %1 = add i64 %b, 12
  %2 = shl i64 %1, 2
  %3 = getelementptr i64, ptr %a, i64 %2
  %4 = load i64, ptr %3, align 8
  ret i64 %4
}

define i64 @lxd_large_offset(ptr %a, i64 %b) {
; RV32-LABEL: lxd_large_offset:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 3
; RV32-NEXT:    add a0, a1, a0
; RV32-NEXT:    lui a1, 23
; RV32-NEXT:    addi a1, a1, 1792
; RV32-NEXT:    add a1, a0, a1
; RV32-NEXT:    lw a0, 0(a1)
; RV32-NEXT:    lw a1, 4(a1)
; RV32-NEXT:    ret
;
; RV32-ZILSX-LABEL: lxd_large_offset:
; RV32-ZILSX:       # %bb.0:
; RV32-ZILSX-NEXT:    slli a1, a1, 3
; RV32-ZILSX-NEXT:    add a0, a1, a0
; RV32-ZILSX-NEXT:    lui a1, 23
; RV32-ZILSX-NEXT:    addi a1, a1, 1792
; RV32-ZILSX-NEXT:    add a1, a0, a1
; RV32-ZILSX-NEXT:    lw a0, 0(a1)
; RV32-ZILSX-NEXT:    lw a1, 4(a1)
; RV32-ZILSX-NEXT:    ret
;
; RV64-LABEL: lxd_large_offset:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 3
; RV64-NEXT:    add a0, a1, a0
; RV64-NEXT:    lui a1, 23
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    ld a0, 1792(a0)
; RV64-NEXT:    ret
;
; RV64-ZILSX-LABEL: lxd_large_offset:
; RV64-ZILSX:       # %bb.0:
; RV64-ZILSX-NEXT:    slli a1, a1, 3
; RV64-ZILSX-NEXT:    add a0, a1, a0
; RV64-ZILSX-NEXT:    lui a1, 23
; RV64-ZILSX-NEXT:    add a0, a0, a1
; RV64-ZILSX-NEXT:    ld a0, 1792(a0)
; RV64-ZILSX-NEXT:    ret
  %1 = add i64 %b, 12000
  %2 = getelementptr i64, ptr %a, i64 %1
  %3 = load i64, ptr %2, align 8
  ret i64 %3
}
