; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: sed 's/iXLen/i32/g' %s | llc -mtriple=riscv32 -verify-machineinstrs \
; RUN:   | FileCheck -check-prefix=RV32 %s
; RUN: sed 's/iXLen/i32/g' %s | llc -mtriple=riscv32 -mattr=+zilxia -verify-machineinstrs \
; RUN:   | FileCheck -check-prefix=RV32-ZILXIA %s
; RUN: sed 's/iXLen/i64/g' %s | llc -mtriple=riscv64 -verify-machineinstrs \
; RUN:   | FileCheck -check-prefix=RV64 %s
; RUN: sed 's/iXLen/i64/g' %s | llc -mtriple=riscv64 -mattr=+zilxia -verify-machineinstrs \
; RUN:   | FileCheck -check-prefix=RV64-ZILXIA %s

define ptr @lbia(ptr %base, ptr %addr.2, i8 %a) {
; RV32-LABEL: lbia:
; RV32:       # %bb.0:
; RV32-NEXT:    lbu a3, 0(a0)
; RV32-NEXT:    addi a0, a0, -1
; RV32-NEXT:    add a2, a3, a2
; RV32-NEXT:    sb a2, 0(a1)
; RV32-NEXT:    ret
;
; RV32-ZILXIA-LABEL: lbia:
; RV32-ZILXIA:       # %bb.0:
; RV32-ZILXIA-NEXT:    lbia a3, (a0), -1
; RV32-ZILXIA-NEXT:    add a2, a3, a2
; RV32-ZILXIA-NEXT:    sb a2, 0(a1)
; RV32-ZILXIA-NEXT:    ret
;
; RV64-LABEL: lbia:
; RV64:       # %bb.0:
; RV64-NEXT:    lbu a3, 0(a0)
; RV64-NEXT:    addi a0, a0, -1
; RV64-NEXT:    add a2, a3, a2
; RV64-NEXT:    sb a2, 0(a1)
; RV64-NEXT:    ret
;
; RV64-ZILXIA-LABEL: lbia:
; RV64-ZILXIA:       # %bb.0:
; RV64-ZILXIA-NEXT:    lbia a3, (a0), -1
; RV64-ZILXIA-NEXT:    add a2, a3, a2
; RV64-ZILXIA-NEXT:    sb a2, 0(a1)
; RV64-ZILXIA-NEXT:    ret
  %addr = getelementptr i8, ptr %base, iXLen 0
  %ld = load i8, ptr %addr
  %addr.1 = getelementptr i8, ptr %base, iXLen -1
  %res = add i8 %ld, %a
  store i8 %res, ptr %addr.2
  ret ptr %addr.1
}

define ptr @lbuia(ptr %base, ptr %addr.2, i32 %a) {
; RV32-LABEL: lbuia:
; RV32:       # %bb.0:
; RV32-NEXT:    lbu a3, 0(a0)
; RV32-NEXT:    addi a0, a0, -1
; RV32-NEXT:    add a2, a3, a2
; RV32-NEXT:    sw a2, 0(a1)
; RV32-NEXT:    ret
;
; RV32-ZILXIA-LABEL: lbuia:
; RV32-ZILXIA:       # %bb.0:
; RV32-ZILXIA-NEXT:    lbuia a3, (a0), -1
; RV32-ZILXIA-NEXT:    add a2, a3, a2
; RV32-ZILXIA-NEXT:    sw a2, 0(a1)
; RV32-ZILXIA-NEXT:    ret
;
; RV64-LABEL: lbuia:
; RV64:       # %bb.0:
; RV64-NEXT:    lbu a3, 0(a0)
; RV64-NEXT:    addi a0, a0, -1
; RV64-NEXT:    add a2, a3, a2
; RV64-NEXT:    sw a2, 0(a1)
; RV64-NEXT:    ret
;
; RV64-ZILXIA-LABEL: lbuia:
; RV64-ZILXIA:       # %bb.0:
; RV64-ZILXIA-NEXT:    lbuia a3, (a0), -1
; RV64-ZILXIA-NEXT:    add a2, a3, a2
; RV64-ZILXIA-NEXT:    sw a2, 0(a1)
; RV64-ZILXIA-NEXT:    ret
  %addr = getelementptr i8, ptr %base, iXLen 0
  %ld = load i8, ptr %addr
  %zext = zext i8 %ld to i32
  %addr.1 = getelementptr i8, ptr %base, iXLen -1
  %res = add i32 %zext, %a
  store i32 %res, ptr %addr.2
  ret ptr %addr.1
}

define ptr @lhia(ptr %base, ptr %addr.2, i16 %a) {
; RV32-LABEL: lhia:
; RV32:       # %bb.0:
; RV32-NEXT:    lh a3, 0(a0)
; RV32-NEXT:    addi a0, a0, -32
; RV32-NEXT:    add a2, a3, a2
; RV32-NEXT:    sh a2, 0(a1)
; RV32-NEXT:    ret
;
; RV32-ZILXIA-LABEL: lhia:
; RV32-ZILXIA:       # %bb.0:
; RV32-ZILXIA-NEXT:    lhia a3, (a0), -16
; RV32-ZILXIA-NEXT:    add a2, a3, a2
; RV32-ZILXIA-NEXT:    sh a2, 0(a1)
; RV32-ZILXIA-NEXT:    ret
;
; RV64-LABEL: lhia:
; RV64:       # %bb.0:
; RV64-NEXT:    lh a3, 0(a0)
; RV64-NEXT:    addi a0, a0, -32
; RV64-NEXT:    add a2, a3, a2
; RV64-NEXT:    sh a2, 0(a1)
; RV64-NEXT:    ret
;
; RV64-ZILXIA-LABEL: lhia:
; RV64-ZILXIA:       # %bb.0:
; RV64-ZILXIA-NEXT:    lhia a3, (a0), -16
; RV64-ZILXIA-NEXT:    add a2, a3, a2
; RV64-ZILXIA-NEXT:    sh a2, 0(a1)
; RV64-ZILXIA-NEXT:    ret
  %addr = getelementptr i16, ptr %base, iXLen 0
  %ld = load i16, ptr %addr
  %addr.1 = getelementptr i16, ptr %base, iXLen -16
  %res = add i16 %ld, %a
  store i16 %res, ptr %addr.2
  ret ptr %addr.1
}

define ptr @lhuia(ptr %base, ptr %addr.2, i32 %a) {
; RV32-LABEL: lhuia:
; RV32:       # %bb.0:
; RV32-NEXT:    lhu a3, 0(a0)
; RV32-NEXT:    addi a0, a0, -32
; RV32-NEXT:    add a2, a3, a2
; RV32-NEXT:    sw a2, 0(a1)
; RV32-NEXT:    ret
;
; RV32-ZILXIA-LABEL: lhuia:
; RV32-ZILXIA:       # %bb.0:
; RV32-ZILXIA-NEXT:    lhuia a3, (a0), -16
; RV32-ZILXIA-NEXT:    add a2, a3, a2
; RV32-ZILXIA-NEXT:    sw a2, 0(a1)
; RV32-ZILXIA-NEXT:    ret
;
; RV64-LABEL: lhuia:
; RV64:       # %bb.0:
; RV64-NEXT:    lhu a3, 0(a0)
; RV64-NEXT:    addi a0, a0, -32
; RV64-NEXT:    add a2, a3, a2
; RV64-NEXT:    sw a2, 0(a1)
; RV64-NEXT:    ret
;
; RV64-ZILXIA-LABEL: lhuia:
; RV64-ZILXIA:       # %bb.0:
; RV64-ZILXIA-NEXT:    lhuia a3, (a0), -16
; RV64-ZILXIA-NEXT:    add a2, a3, a2
; RV64-ZILXIA-NEXT:    sw a2, 0(a1)
; RV64-ZILXIA-NEXT:    ret
  %addr = getelementptr i16, ptr %base, iXLen 0
  %ld = load i16, ptr %addr
  %zext = zext i16 %ld to i32
  %addr.1 = getelementptr i16, ptr %base, iXLen -16
  %res = add i32 %zext, %a
  store i32 %res, ptr %addr.2
  ret ptr %addr.1
}

define ptr @lwia(ptr %base, ptr %addr.2, i32 %a) {
; RV32-LABEL: lwia:
; RV32:       # %bb.0:
; RV32-NEXT:    lw a3, 0(a0)
; RV32-NEXT:    addi a0, a0, -64
; RV32-NEXT:    add a2, a3, a2
; RV32-NEXT:    sw a2, 0(a1)
; RV32-NEXT:    ret
;
; RV32-ZILXIA-LABEL: lwia:
; RV32-ZILXIA:       # %bb.0:
; RV32-ZILXIA-NEXT:    lwia a3, (a0), -16
; RV32-ZILXIA-NEXT:    add a2, a3, a2
; RV32-ZILXIA-NEXT:    sw a2, 0(a1)
; RV32-ZILXIA-NEXT:    ret
;
; RV64-LABEL: lwia:
; RV64:       # %bb.0:
; RV64-NEXT:    lw a3, 0(a0)
; RV64-NEXT:    addi a0, a0, -64
; RV64-NEXT:    add a2, a3, a2
; RV64-NEXT:    sw a2, 0(a1)
; RV64-NEXT:    ret
;
; RV64-ZILXIA-LABEL: lwia:
; RV64-ZILXIA:       # %bb.0:
; RV64-ZILXIA-NEXT:    lwia a3, (a0), -16
; RV64-ZILXIA-NEXT:    add a2, a3, a2
; RV64-ZILXIA-NEXT:    sw a2, 0(a1)
; RV64-ZILXIA-NEXT:    ret
  %addr = getelementptr i32, ptr %base, iXLen 0
  %ld = load i32, ptr %addr
  %addr.1 = getelementptr i32, ptr %base, iXLen -16
  %res = add i32 %ld, %a
  store i32 %res, ptr %addr.2
  ret ptr %addr.1
}

define ptr @lwuia(ptr %base, ptr %addr.2, i64 %a) {
; RV32-LABEL: lwuia:
; RV32:       # %bb.0:
; RV32-NEXT:    lw a4, 0(a0)
; RV32-NEXT:    addi a0, a0, -64
; RV32-NEXT:    add a2, a4, a2
; RV32-NEXT:    sltu a4, a2, a4
; RV32-NEXT:    add a3, a3, a4
; RV32-NEXT:    sw a2, 0(a1)
; RV32-NEXT:    sw a3, 4(a1)
; RV32-NEXT:    ret
;
; RV32-ZILXIA-LABEL: lwuia:
; RV32-ZILXIA:       # %bb.0:
; RV32-ZILXIA-NEXT:    lwia a4, (a0), -16
; RV32-ZILXIA-NEXT:    add a2, a4, a2
; RV32-ZILXIA-NEXT:    sltu a4, a2, a4
; RV32-ZILXIA-NEXT:    add a3, a3, a4
; RV32-ZILXIA-NEXT:    sw a2, 0(a1)
; RV32-ZILXIA-NEXT:    sw a3, 4(a1)
; RV32-ZILXIA-NEXT:    ret
;
; RV64-LABEL: lwuia:
; RV64:       # %bb.0:
; RV64-NEXT:    lwu a3, 0(a0)
; RV64-NEXT:    addi a0, a0, -64
; RV64-NEXT:    add a2, a3, a2
; RV64-NEXT:    sd a2, 0(a1)
; RV64-NEXT:    ret
;
; RV64-ZILXIA-LABEL: lwuia:
; RV64-ZILXIA:       # %bb.0:
; RV64-ZILXIA-NEXT:    lwuia a3, (a0), -16
; RV64-ZILXIA-NEXT:    add a2, a3, a2
; RV64-ZILXIA-NEXT:    sd a2, 0(a1)
; RV64-ZILXIA-NEXT:    ret
  %addr = getelementptr i32, ptr %base, iXLen 0
  %ld = load i32, ptr %addr
  %zext = zext i32 %ld to i64
  %addr.1 = getelementptr i32, ptr %base, iXLen -16
  %res = add i64 %zext, %a
  store i64 %res, ptr %addr.2
  ret ptr %addr.1
}

define ptr @ldia(ptr %base, ptr %addr.2, i64 %a) {
; RV32-LABEL: ldia:
; RV32:       # %bb.0:
; RV32-NEXT:    lw a4, 4(a0)
; RV32-NEXT:    lw a5, 0(a0)
; RV32-NEXT:    addi a0, a0, -128
; RV32-NEXT:    add a3, a4, a3
; RV32-NEXT:    add a2, a5, a2
; RV32-NEXT:    sltu a4, a2, a5
; RV32-NEXT:    add a3, a3, a4
; RV32-NEXT:    sw a2, 0(a1)
; RV32-NEXT:    sw a3, 4(a1)
; RV32-NEXT:    ret
;
; RV32-ZILXIA-LABEL: ldia:
; RV32-ZILXIA:       # %bb.0:
; RV32-ZILXIA-NEXT:    lw a4, 4(a0)
; RV32-ZILXIA-NEXT:    lw a5, 0(a0)
; RV32-ZILXIA-NEXT:    addi a0, a0, -128
; RV32-ZILXIA-NEXT:    add a3, a4, a3
; RV32-ZILXIA-NEXT:    add a2, a5, a2
; RV32-ZILXIA-NEXT:    sltu a4, a2, a5
; RV32-ZILXIA-NEXT:    add a3, a3, a4
; RV32-ZILXIA-NEXT:    sw a2, 0(a1)
; RV32-ZILXIA-NEXT:    sw a3, 4(a1)
; RV32-ZILXIA-NEXT:    ret
;
; RV64-LABEL: ldia:
; RV64:       # %bb.0:
; RV64-NEXT:    ld a3, 0(a0)
; RV64-NEXT:    addi a0, a0, -128
; RV64-NEXT:    add a2, a3, a2
; RV64-NEXT:    sd a2, 0(a1)
; RV64-NEXT:    ret
;
; RV64-ZILXIA-LABEL: ldia:
; RV64-ZILXIA:       # %bb.0:
; RV64-ZILXIA-NEXT:    ldia a3, (a0), -16
; RV64-ZILXIA-NEXT:    add a2, a3, a2
; RV64-ZILXIA-NEXT:    sd a2, 0(a1)
; RV64-ZILXIA-NEXT:    ret
  %addr = getelementptr i64, ptr %base, iXLen 0
  %ld = load i64, ptr %addr
  %addr.1 = getelementptr i64, ptr %base, iXLen -16
  %res = add i64 %ld, %a
  store i64 %res, ptr %addr.2
  ret ptr %addr.1
}
