; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: sed 's/iXLen/i32/g' %s | llc -mtriple=riscv32 -verify-machineinstrs \
; RUN:   | FileCheck -check-prefix=RV32 %s
; RUN: sed 's/iXLen/i32/g' %s | llc -mtriple=riscv32 -mattr=+zilxib -verify-machineinstrs \
; RUN:   | FileCheck -check-prefix=RV32-ZILXIB %s
; RUN: sed 's/iXLen/i64/g' %s | llc -mtriple=riscv64 -verify-machineinstrs \
; RUN:   | FileCheck -check-prefix=RV64 %s
; RUN: sed 's/iXLen/i64/g' %s | llc -mtriple=riscv64 -mattr=+zilxib -verify-machineinstrs \
; RUN:   | FileCheck -check-prefix=RV64-ZILXIB %s

define ptr @lbib(ptr %base, i8 %a) {
; RV32-LABEL: lbib:
; RV32:       # %bb.0:
; RV32-NEXT:    lbu a3, 1(a0)
; RV32-NEXT:    addi a2, a0, 1
; RV32-NEXT:    add a1, a3, a1
; RV32-NEXT:    sb a1, 2(a0)
; RV32-NEXT:    mv a0, a2
; RV32-NEXT:    ret
;
; RV32-ZILXIB-LABEL: lbib:
; RV32-ZILXIB:       # %bb.0:
; RV32-ZILXIB-NEXT:    lbib a2, (a0), 1
; RV32-ZILXIB-NEXT:    add a1, a2, a1
; RV32-ZILXIB-NEXT:    sb a1, 1(a0)
; RV32-ZILXIB-NEXT:    ret
;
; RV64-LABEL: lbib:
; RV64:       # %bb.0:
; RV64-NEXT:    lbu a3, 1(a0)
; RV64-NEXT:    addi a2, a0, 1
; RV64-NEXT:    add a1, a3, a1
; RV64-NEXT:    sb a1, 2(a0)
; RV64-NEXT:    mv a0, a2
; RV64-NEXT:    ret
;
; RV64-ZILXIB-LABEL: lbib:
; RV64-ZILXIB:       # %bb.0:
; RV64-ZILXIB-NEXT:    lbib a2, (a0), 1
; RV64-ZILXIB-NEXT:    add a1, a2, a1
; RV64-ZILXIB-NEXT:    sb a1, 1(a0)
; RV64-ZILXIB-NEXT:    ret
  %addr = getelementptr i8, ptr %base, iXLen 1
  %ld = load i8, ptr %addr
  %addr.1 = getelementptr i8, ptr %base, iXLen 2
  %res = add i8 %ld, %a
  store i8 %res, ptr %addr.1
  ret ptr %addr
}

define ptr @lbuib(ptr %base, i32 %a, ptr %addr.1) {
; RV32-LABEL: lbuib:
; RV32:       # %bb.0:
; RV32-NEXT:    lbu a3, 1(a0)
; RV32-NEXT:    addi a0, a0, 1
; RV32-NEXT:    add a1, a3, a1
; RV32-NEXT:    sw a1, 0(a2)
; RV32-NEXT:    ret
;
; RV32-ZILXIB-LABEL: lbuib:
; RV32-ZILXIB:       # %bb.0:
; RV32-ZILXIB-NEXT:    lbuib a3, (a0), 1
; RV32-ZILXIB-NEXT:    add a1, a3, a1
; RV32-ZILXIB-NEXT:    sw a1, 0(a2)
; RV32-ZILXIB-NEXT:    ret
;
; RV64-LABEL: lbuib:
; RV64:       # %bb.0:
; RV64-NEXT:    lbu a3, 1(a0)
; RV64-NEXT:    addi a0, a0, 1
; RV64-NEXT:    add a1, a3, a1
; RV64-NEXT:    sw a1, 0(a2)
; RV64-NEXT:    ret
;
; RV64-ZILXIB-LABEL: lbuib:
; RV64-ZILXIB:       # %bb.0:
; RV64-ZILXIB-NEXT:    lbuib a3, (a0), 1
; RV64-ZILXIB-NEXT:    add a1, a3, a1
; RV64-ZILXIB-NEXT:    sw a1, 0(a2)
; RV64-ZILXIB-NEXT:    ret
  %addr = getelementptr i8, ptr %base, iXLen 1
  %ld = load i8, ptr %addr
  %zext = zext i8 %ld to i32
  %res = add i32 %zext, %a
  store i32 %res, ptr %addr.1
  ret ptr %addr
}

define ptr @lhib(ptr %base, i16 %a) {
; RV32-LABEL: lhib:
; RV32:       # %bb.0:
; RV32-NEXT:    lh a3, 2(a0)
; RV32-NEXT:    addi a2, a0, 2
; RV32-NEXT:    add a1, a3, a1
; RV32-NEXT:    sh a1, 4(a0)
; RV32-NEXT:    mv a0, a2
; RV32-NEXT:    ret
;
; RV32-ZILXIB-LABEL: lhib:
; RV32-ZILXIB:       # %bb.0:
; RV32-ZILXIB-NEXT:    lhib a2, (a0), 1
; RV32-ZILXIB-NEXT:    add a1, a2, a1
; RV32-ZILXIB-NEXT:    sh a1, 2(a0)
; RV32-ZILXIB-NEXT:    ret
;
; RV64-LABEL: lhib:
; RV64:       # %bb.0:
; RV64-NEXT:    lh a3, 2(a0)
; RV64-NEXT:    addi a2, a0, 2
; RV64-NEXT:    add a1, a3, a1
; RV64-NEXT:    sh a1, 4(a0)
; RV64-NEXT:    mv a0, a2
; RV64-NEXT:    ret
;
; RV64-ZILXIB-LABEL: lhib:
; RV64-ZILXIB:       # %bb.0:
; RV64-ZILXIB-NEXT:    lhib a2, (a0), 1
; RV64-ZILXIB-NEXT:    add a1, a2, a1
; RV64-ZILXIB-NEXT:    sh a1, 2(a0)
; RV64-ZILXIB-NEXT:    ret
  %addr = getelementptr i16, ptr %base, iXLen 1
  %ld = load i16, ptr %addr
  %addr.1 = getelementptr i16, ptr %base, iXLen 2
  %res = add i16 %ld, %a
  store i16 %res, ptr %addr.1
  ret ptr %addr
}

define ptr @lhuib(ptr %base, i32 %a, ptr %addr.1) {
; RV32-LABEL: lhuib:
; RV32:       # %bb.0:
; RV32-NEXT:    lhu a3, 2(a0)
; RV32-NEXT:    addi a0, a0, 2
; RV32-NEXT:    add a1, a3, a1
; RV32-NEXT:    sw a1, 0(a2)
; RV32-NEXT:    ret
;
; RV32-ZILXIB-LABEL: lhuib:
; RV32-ZILXIB:       # %bb.0:
; RV32-ZILXIB-NEXT:    lhuib a3, (a0), 1
; RV32-ZILXIB-NEXT:    add a1, a3, a1
; RV32-ZILXIB-NEXT:    sw a1, 0(a2)
; RV32-ZILXIB-NEXT:    ret
;
; RV64-LABEL: lhuib:
; RV64:       # %bb.0:
; RV64-NEXT:    lhu a3, 2(a0)
; RV64-NEXT:    addi a0, a0, 2
; RV64-NEXT:    add a1, a3, a1
; RV64-NEXT:    sw a1, 0(a2)
; RV64-NEXT:    ret
;
; RV64-ZILXIB-LABEL: lhuib:
; RV64-ZILXIB:       # %bb.0:
; RV64-ZILXIB-NEXT:    lhuib a3, (a0), 1
; RV64-ZILXIB-NEXT:    add a1, a3, a1
; RV64-ZILXIB-NEXT:    sw a1, 0(a2)
; RV64-ZILXIB-NEXT:    ret
  %addr = getelementptr i16, ptr %base, iXLen 1
  %ld = load i16, ptr %addr
  %zext = zext i16 %ld to i32
  %res = add i32 %zext, %a
  store i32 %res, ptr %addr.1
  ret ptr %addr
}

define ptr @lwib(ptr %base, i32 %a) {
; RV32-LABEL: lwib:
; RV32:       # %bb.0:
; RV32-NEXT:    lw a3, 4(a0)
; RV32-NEXT:    addi a2, a0, 4
; RV32-NEXT:    add a1, a3, a1
; RV32-NEXT:    sw a1, 8(a0)
; RV32-NEXT:    mv a0, a2
; RV32-NEXT:    ret
;
; RV32-ZILXIB-LABEL: lwib:
; RV32-ZILXIB:       # %bb.0:
; RV32-ZILXIB-NEXT:    lwib a2, (a0), 1
; RV32-ZILXIB-NEXT:    add a1, a2, a1
; RV32-ZILXIB-NEXT:    sw a1, 4(a0)
; RV32-ZILXIB-NEXT:    ret
;
; RV64-LABEL: lwib:
; RV64:       # %bb.0:
; RV64-NEXT:    lw a3, 4(a0)
; RV64-NEXT:    addi a2, a0, 4
; RV64-NEXT:    add a1, a3, a1
; RV64-NEXT:    sw a1, 8(a0)
; RV64-NEXT:    mv a0, a2
; RV64-NEXT:    ret
;
; RV64-ZILXIB-LABEL: lwib:
; RV64-ZILXIB:       # %bb.0:
; RV64-ZILXIB-NEXT:    lwib a2, (a0), 1
; RV64-ZILXIB-NEXT:    add a1, a2, a1
; RV64-ZILXIB-NEXT:    sw a1, 4(a0)
; RV64-ZILXIB-NEXT:    ret
  %addr = getelementptr i32, ptr %base, iXLen 1
  %ld = load i32, ptr %addr
  %addr.1 = getelementptr i32, ptr %base, iXLen 2
  %res = add i32 %ld, %a
  store i32 %res, ptr %addr.1
  ret ptr %addr
}

define ptr @lwuib(ptr %base, i64 %a, ptr %addr.1) {
; RV32-LABEL: lwuib:
; RV32:       # %bb.0:
; RV32-NEXT:    lw a4, 4(a0)
; RV32-NEXT:    addi a0, a0, 4
; RV32-NEXT:    add a1, a4, a1
; RV32-NEXT:    sltu a4, a1, a4
; RV32-NEXT:    add a2, a2, a4
; RV32-NEXT:    sw a1, 0(a3)
; RV32-NEXT:    sw a2, 4(a3)
; RV32-NEXT:    ret
;
; RV32-ZILXIB-LABEL: lwuib:
; RV32-ZILXIB:       # %bb.0:
; RV32-ZILXIB-NEXT:    lwib a4, (a0), 1
; RV32-ZILXIB-NEXT:    add a1, a4, a1
; RV32-ZILXIB-NEXT:    sltu a4, a1, a4
; RV32-ZILXIB-NEXT:    add a2, a2, a4
; RV32-ZILXIB-NEXT:    sw a1, 0(a3)
; RV32-ZILXIB-NEXT:    sw a2, 4(a3)
; RV32-ZILXIB-NEXT:    ret
;
; RV64-LABEL: lwuib:
; RV64:       # %bb.0:
; RV64-NEXT:    lwu a3, 4(a0)
; RV64-NEXT:    addi a0, a0, 4
; RV64-NEXT:    add a1, a3, a1
; RV64-NEXT:    sd a1, 0(a2)
; RV64-NEXT:    ret
;
; RV64-ZILXIB-LABEL: lwuib:
; RV64-ZILXIB:       # %bb.0:
; RV64-ZILXIB-NEXT:    lwuib a3, (a0), 1
; RV64-ZILXIB-NEXT:    add a1, a3, a1
; RV64-ZILXIB-NEXT:    sd a1, 0(a2)
; RV64-ZILXIB-NEXT:    ret
  %addr = getelementptr i32, ptr %base, iXLen 1
  %ld = load i32, ptr %addr
  %zext = zext i32 %ld to i64
  %res = add i64 %zext, %a
  store i64 %res, ptr %addr.1
  ret ptr %addr
}

define ptr @ldib(ptr %base, i64 %a) {
; RV32-LABEL: ldib:
; RV32:       # %bb.0:
; RV32-NEXT:    lw a4, 12(a0)
; RV32-NEXT:    lw a5, 8(a0)
; RV32-NEXT:    addi a3, a0, 8
; RV32-NEXT:    add a2, a4, a2
; RV32-NEXT:    add a1, a5, a1
; RV32-NEXT:    sltu a4, a1, a5
; RV32-NEXT:    add a2, a2, a4
; RV32-NEXT:    sw a1, 16(a0)
; RV32-NEXT:    sw a2, 20(a0)
; RV32-NEXT:    mv a0, a3
; RV32-NEXT:    ret
;
; RV32-ZILXIB-LABEL: ldib:
; RV32-ZILXIB:       # %bb.0:
; RV32-ZILXIB-NEXT:    lwib a3, (a0), 2
; RV32-ZILXIB-NEXT:    lw a4, 4(a0)
; RV32-ZILXIB-NEXT:    add a1, a3, a1
; RV32-ZILXIB-NEXT:    sltu a3, a1, a3
; RV32-ZILXIB-NEXT:    add a2, a2, a3
; RV32-ZILXIB-NEXT:    add a2, a4, a2
; RV32-ZILXIB-NEXT:    sw a1, 8(a0)
; RV32-ZILXIB-NEXT:    sw a2, 12(a0)
; RV32-ZILXIB-NEXT:    ret
;
; RV64-LABEL: ldib:
; RV64:       # %bb.0:
; RV64-NEXT:    ld a3, 8(a0)
; RV64-NEXT:    addi a2, a0, 8
; RV64-NEXT:    add a1, a3, a1
; RV64-NEXT:    sd a1, 16(a0)
; RV64-NEXT:    mv a0, a2
; RV64-NEXT:    ret
;
; RV64-ZILXIB-LABEL: ldib:
; RV64-ZILXIB:       # %bb.0:
; RV64-ZILXIB-NEXT:    ldib a2, (a0), 1
; RV64-ZILXIB-NEXT:    add a1, a2, a1
; RV64-ZILXIB-NEXT:    sd a1, 8(a0)
; RV64-ZILXIB-NEXT:    ret
  %addr = getelementptr i64, ptr %base, iXLen 1
  %ld = load i64, ptr %addr
  %addr.1 = getelementptr i64, ptr %base, iXLen 2
  %res = add i64 %ld, %a
  store i64 %res, ptr %addr.1
  ret ptr %addr
}
