; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: sed 's/iXLen/i32/g' %s | llc -mtriple=riscv32 -verify-machineinstrs \
; RUN:   | FileCheck -check-prefix=RV32 %s
; RUN: sed 's/iXLen/i32/g' %s | llc -mtriple=riscv32 -mattr=+zisx -verify-machineinstrs \
; RUN:   | FileCheck -check-prefix=RV32-ZISX %s
; RUN: sed 's/iXLen/i64/g' %s | llc -mtriple=riscv64 -verify-machineinstrs \
; RUN:   | FileCheck -check-prefix=RV64 %s
; RUN: sed 's/iXLen/i64/g' %s | llc -mtriple=riscv64 -mattr=+zisx -verify-machineinstrs \
; RUN:   | FileCheck -check-prefix=RV64-ZISX %s

;------------------------------------------------------------------------------
; Unscaled Store
;------------------------------------------------------------------------------

define void @sxb(ptr %a, iXLen %b, i8 %c) {
; RV32-LABEL: sxb:
; RV32:       # %bb.0:
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    sb a2, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZISX-LABEL: sxb:
; RV32-ZISX:       # %bb.0:
; RV32-ZISX-NEXT:    sxb a2, (a0), a1
; RV32-ZISX-NEXT:    ret
;
; RV64-LABEL: sxb:
; RV64:       # %bb.0:
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    sb a2, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZISX-LABEL: sxb:
; RV64-ZISX:       # %bb.0:
; RV64-ZISX-NEXT:    sxb a2, (a0), a1
; RV64-ZISX-NEXT:    ret
  %addr = getelementptr i8, ptr %a, iXLen %b
  store i8 %c, ptr %addr, align 1
  ret void
}

define void @sxb_uw(ptr %a, i32 %b, i8 %c) {
; RV32-LABEL: sxb_uw:
; RV32:       # %bb.0:
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    sb a2, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZISX-LABEL: sxb_uw:
; RV32-ZISX:       # %bb.0:
; RV32-ZISX-NEXT:    sxb a2, (a0), a1
; RV32-ZISX-NEXT:    ret
;
; RV64-LABEL: sxb_uw:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 32
; RV64-NEXT:    srli a1, a1, 32
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    sb a2, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZISX-LABEL: sxb_uw:
; RV64-ZISX:       # %bb.0:
; RV64-ZISX-NEXT:    sxb.uw a2, (a0), a1
; RV64-ZISX-NEXT:    ret
  %index = zext i32 %b to i64
  %addr = getelementptr i8, ptr %a, i64 %index
  store i8 %c, ptr %addr, align 1
  ret void
}

; Why using .s?
define void @sxh(ptr %a, iXLen %b, i16 %c) {
; RV32-LABEL: sxh:
; RV32:       # %bb.0:
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    sh a2, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZISX-LABEL: sxh:
; RV32-ZISX:       # %bb.0:
; RV32-ZISX-NEXT:    sxh a2, (a0), a1
; RV32-ZISX-NEXT:    ret
;
; RV64-LABEL: sxh:
; RV64:       # %bb.0:
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    sh a2, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZISX-LABEL: sxh:
; RV64-ZISX:       # %bb.0:
; RV64-ZISX-NEXT:    sxh a2, (a0), a1
; RV64-ZISX-NEXT:    ret
  %addr = getelementptr i8, ptr %a, iXLen %b
  store i16 %c, ptr %addr, align 2
  ret void
}

define void @sxh_uw(ptr %a, i32 %b, i16 %c) {
; RV32-LABEL: sxh_uw:
; RV32:       # %bb.0:
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    sh a2, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZISX-LABEL: sxh_uw:
; RV32-ZISX:       # %bb.0:
; RV32-ZISX-NEXT:    sxh a2, (a0), a1
; RV32-ZISX-NEXT:    ret
;
; RV64-LABEL: sxh_uw:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 32
; RV64-NEXT:    srli a1, a1, 32
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    sh a2, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZISX-LABEL: sxh_uw:
; RV64-ZISX:       # %bb.0:
; RV64-ZISX-NEXT:    sxh.uw a2, (a0), a1
; RV64-ZISX-NEXT:    ret
  %index = zext i32 %b to i64
  %addr = getelementptr i8, ptr %a, i64 %index
  store i16 %c, ptr %addr, align 2
  ret void
}

define void @sxw(ptr %a, iXLen %b, i32 %c) {
; RV32-LABEL: sxw:
; RV32:       # %bb.0:
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    sw a2, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZISX-LABEL: sxw:
; RV32-ZISX:       # %bb.0:
; RV32-ZISX-NEXT:    sxw a2, (a0), a1
; RV32-ZISX-NEXT:    ret
;
; RV64-LABEL: sxw:
; RV64:       # %bb.0:
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    sw a2, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZISX-LABEL: sxw:
; RV64-ZISX:       # %bb.0:
; RV64-ZISX-NEXT:    sxw a2, (a0), a1
; RV64-ZISX-NEXT:    ret
  %addr = getelementptr i8, ptr %a, iXLen %b
  store i32 %c, ptr %addr, align 4
  ret void
}

define void @sxw_uw(ptr %a, i32 %b, i32 %c) {
; RV32-LABEL: sxw_uw:
; RV32:       # %bb.0:
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    sw a2, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZISX-LABEL: sxw_uw:
; RV32-ZISX:       # %bb.0:
; RV32-ZISX-NEXT:    sxw a2, (a0), a1
; RV32-ZISX-NEXT:    ret
;
; RV64-LABEL: sxw_uw:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 32
; RV64-NEXT:    srli a1, a1, 32
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    sw a2, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZISX-LABEL: sxw_uw:
; RV64-ZISX:       # %bb.0:
; RV64-ZISX-NEXT:    sxw.uw a2, (a0), a1
; RV64-ZISX-NEXT:    ret
  %index = zext i32 %b to i64
  %addr = getelementptr i8, ptr %a, i64 %index
  store i32 %c, ptr %addr, align 4
  ret void
}

define void @sxd(ptr %a, iXLen %b, i64 %c) {
; RV32-LABEL: sxd:
; RV32:       # %bb.0:
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    sw a2, 0(a0)
; RV32-NEXT:    sw a3, 4(a0)
; RV32-NEXT:    ret
;
; RV32-ZISX-LABEL: sxd:
; RV32-ZISX:       # %bb.0:
; RV32-ZISX-NEXT:    add a0, a0, a1
; RV32-ZISX-NEXT:    sw a2, 0(a0)
; RV32-ZISX-NEXT:    sw a3, 4(a0)
; RV32-ZISX-NEXT:    ret
;
; RV64-LABEL: sxd:
; RV64:       # %bb.0:
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    sd a2, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZISX-LABEL: sxd:
; RV64-ZISX:       # %bb.0:
; RV64-ZISX-NEXT:    sxd a2, (a0), a1
; RV64-ZISX-NEXT:    ret
  %addr = getelementptr i8, ptr %a, iXLen %b
  store i64 %c, ptr %addr, align 8
  ret void
}

define void @sxd_uw(ptr %a, i32 %b, i64 %c) {
; RV32-LABEL: sxd_uw:
; RV32:       # %bb.0:
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    sw a2, 0(a0)
; RV32-NEXT:    sw a3, 4(a0)
; RV32-NEXT:    ret
;
; RV32-ZISX-LABEL: sxd_uw:
; RV32-ZISX:       # %bb.0:
; RV32-ZISX-NEXT:    add a0, a0, a1
; RV32-ZISX-NEXT:    sw a2, 0(a0)
; RV32-ZISX-NEXT:    sw a3, 4(a0)
; RV32-ZISX-NEXT:    ret
;
; RV64-LABEL: sxd_uw:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 32
; RV64-NEXT:    srli a1, a1, 32
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    sd a2, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZISX-LABEL: sxd_uw:
; RV64-ZISX:       # %bb.0:
; RV64-ZISX-NEXT:    sxd.uw a2, (a0), a1
; RV64-ZISX-NEXT:    ret
  %index = zext i32 %b to i64
  %addr = getelementptr i8, ptr %a, i64 %index
  store i64 %c, ptr %addr, align 8
  ret void
}

;------------------------------------------------------------------------------
; Scaled Store
;------------------------------------------------------------------------------

define void @sxh_s(ptr %a, iXLen %b, i16 %c) {
; RV32-LABEL: sxh_s:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 1
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    sh a2, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZISX-LABEL: sxh_s:
; RV32-ZISX:       # %bb.0:
; RV32-ZISX-NEXT:    sxh.s a2, (a0), a1
; RV32-ZISX-NEXT:    ret
;
; RV64-LABEL: sxh_s:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 1
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    sh a2, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZISX-LABEL: sxh_s:
; RV64-ZISX:       # %bb.0:
; RV64-ZISX-NEXT:    sxh.s a2, (a0), a1
; RV64-ZISX-NEXT:    ret
  %addr = getelementptr i16, ptr %a, iXLen %b
  store i16 %c, ptr %addr, align 2
  ret void
}

define void @sxh_s_uw(ptr %a, i32 %b, i16 %c) {
; RV32-LABEL: sxh_s_uw:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 1
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    sh a2, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZISX-LABEL: sxh_s_uw:
; RV32-ZISX:       # %bb.0:
; RV32-ZISX-NEXT:    sxh.s a2, (a0), a1
; RV32-ZISX-NEXT:    ret
;
; RV64-LABEL: sxh_s_uw:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 32
; RV64-NEXT:    srli a1, a1, 31
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    sh a2, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZISX-LABEL: sxh_s_uw:
; RV64-ZISX:       # %bb.0:
; RV64-ZISX-NEXT:    sxh.s.uw a2, (a0), a1
; RV64-ZISX-NEXT:    ret
  %index = zext i32 %b to i64
  %addr = getelementptr i16, ptr %a, i64 %index
  store i16 %c, ptr %addr, align 2
  ret void
}

define void @sxw_s(ptr %a, iXLen %b, i32 %c) {
; RV32-LABEL: sxw_s:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 2
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    sw a2, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZISX-LABEL: sxw_s:
; RV32-ZISX:       # %bb.0:
; RV32-ZISX-NEXT:    sxw.s a2, (a0), a1
; RV32-ZISX-NEXT:    ret
;
; RV64-LABEL: sxw_s:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 2
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    sw a2, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZISX-LABEL: sxw_s:
; RV64-ZISX:       # %bb.0:
; RV64-ZISX-NEXT:    sxw.s a2, (a0), a1
; RV64-ZISX-NEXT:    ret
  %addr = getelementptr i32, ptr %a, iXLen %b
  store i32 %c, ptr %addr, align 4
  ret void
}

define void @sxw_s_uw(ptr %a, i32 %b, i32 %c) {
; RV32-LABEL: sxw_s_uw:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 2
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    sw a2, 0(a0)
; RV32-NEXT:    ret
;
; RV32-ZISX-LABEL: sxw_s_uw:
; RV32-ZISX:       # %bb.0:
; RV32-ZISX-NEXT:    sxw.s a2, (a0), a1
; RV32-ZISX-NEXT:    ret
;
; RV64-LABEL: sxw_s_uw:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 32
; RV64-NEXT:    srli a1, a1, 30
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    sw a2, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZISX-LABEL: sxw_s_uw:
; RV64-ZISX:       # %bb.0:
; RV64-ZISX-NEXT:    sxw.s.uw a2, (a0), a1
; RV64-ZISX-NEXT:    ret
  %index = zext i32 %b to i64
  %addr = getelementptr i32, ptr %a, i64 %index
  store i32 %c, ptr %addr, align 4
  ret void
}

define void @sxd_s(ptr %a, iXLen %b, i64 %c) {
; RV32-LABEL: sxd_s:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 3
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    sw a2, 0(a0)
; RV32-NEXT:    sw a3, 4(a0)
; RV32-NEXT:    ret
;
; RV32-ZISX-LABEL: sxd_s:
; RV32-ZISX:       # %bb.0:
; RV32-ZISX-NEXT:    slli a1, a1, 3
; RV32-ZISX-NEXT:    add a0, a0, a1
; RV32-ZISX-NEXT:    sw a2, 0(a0)
; RV32-ZISX-NEXT:    sw a3, 4(a0)
; RV32-ZISX-NEXT:    ret
;
; RV64-LABEL: sxd_s:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 3
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    sd a2, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZISX-LABEL: sxd_s:
; RV64-ZISX:       # %bb.0:
; RV64-ZISX-NEXT:    sxd.s a2, (a0), a1
; RV64-ZISX-NEXT:    ret
  %addr = getelementptr i64, ptr %a, iXLen %b
  store i64 %c, ptr %addr, align 8
  ret void
}

define void @sxd_s_uw(ptr %a, i32 %b, i64 %c) {
; RV32-LABEL: sxd_s_uw:
; RV32:       # %bb.0:
; RV32-NEXT:    slli a1, a1, 3
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    sw a2, 0(a0)
; RV32-NEXT:    sw a3, 4(a0)
; RV32-NEXT:    ret
;
; RV32-ZISX-LABEL: sxd_s_uw:
; RV32-ZISX:       # %bb.0:
; RV32-ZISX-NEXT:    slli a1, a1, 3
; RV32-ZISX-NEXT:    add a0, a0, a1
; RV32-ZISX-NEXT:    sw a2, 0(a0)
; RV32-ZISX-NEXT:    sw a3, 4(a0)
; RV32-ZISX-NEXT:    ret
;
; RV64-LABEL: sxd_s_uw:
; RV64:       # %bb.0:
; RV64-NEXT:    slli a1, a1, 32
; RV64-NEXT:    srli a1, a1, 29
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    sd a2, 0(a0)
; RV64-NEXT:    ret
;
; RV64-ZISX-LABEL: sxd_s_uw:
; RV64-ZISX:       # %bb.0:
; RV64-ZISX-NEXT:    sxd.s.uw a2, (a0), a1
; RV64-ZISX-NEXT:    ret
  %index = zext i32 %b to i64
  %addr = getelementptr i64, ptr %a, i64 %index
  store i64 %c, ptr %addr, align 8
  ret void
}
