; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: sed 's/iXLen/i32/g' %s | llc -mtriple=riscv32 -verify-machineinstrs \
; RUN:   | FileCheck -check-prefix=RV32 %s
; RUN: sed 's/iXLen/i32/g' %s | llc -mtriple=riscv32 -mattr=+zisxia -verify-machineinstrs \
; RUN:   | FileCheck -check-prefix=RV32-ZISXIA %s
; RUN: sed 's/iXLen/i64/g' %s | llc -mtriple=riscv64 -verify-machineinstrs \
; RUN:   | FileCheck -check-prefix=RV64 %s
; RUN: sed 's/iXLen/i64/g' %s | llc -mtriple=riscv64 -mattr=+zisxia -verify-machineinstrs \
; RUN:   | FileCheck -check-prefix=RV64-ZISXIA %s

define ptr @sbia(ptr %base, i8 %a, i8 %b) {
; RV32-LABEL: sbia:
; RV32:       # %bb.0:
; RV32-NEXT:    addi a3, a0, 1
; RV32-NEXT:    add a1, a1, a2
; RV32-NEXT:    sb a1, 0(a0)
; RV32-NEXT:    mv a0, a3
; RV32-NEXT:    ret
;
; RV32-ZISXIA-LABEL: sbia:
; RV32-ZISXIA:       # %bb.0:
; RV32-ZISXIA-NEXT:    add a1, a1, a2
; RV32-ZISXIA-NEXT:    sbia a1, (a0), 1
; RV32-ZISXIA-NEXT:    ret
;
; RV64-LABEL: sbia:
; RV64:       # %bb.0:
; RV64-NEXT:    addi a3, a0, 1
; RV64-NEXT:    add a1, a1, a2
; RV64-NEXT:    sb a1, 0(a0)
; RV64-NEXT:    mv a0, a3
; RV64-NEXT:    ret
;
; RV64-ZISXIA-LABEL: sbia:
; RV64-ZISXIA:       # %bb.0:
; RV64-ZISXIA-NEXT:    add a1, a1, a2
; RV64-ZISXIA-NEXT:    sbia a1, (a0), 1
; RV64-ZISXIA-NEXT:    ret
  %addr.1 = getelementptr i8, ptr %base, iXLen 1
  %res = add i8 %a, %b
  store i8 %res, ptr %base
  ret ptr %addr.1
}

define ptr @shia(ptr %base, i16 %a, i16 %b) {
; RV32-LABEL: shia:
; RV32:       # %bb.0:
; RV32-NEXT:    addi a3, a0, -18
; RV32-NEXT:    add a1, a1, a2
; RV32-NEXT:    sh a1, 0(a0)
; RV32-NEXT:    mv a0, a3
; RV32-NEXT:    ret
;
; RV32-ZISXIA-LABEL: shia:
; RV32-ZISXIA:       # %bb.0:
; RV32-ZISXIA-NEXT:    add a1, a1, a2
; RV32-ZISXIA-NEXT:    shia a1, (a0), -9
; RV32-ZISXIA-NEXT:    ret
;
; RV64-LABEL: shia:
; RV64:       # %bb.0:
; RV64-NEXT:    addi a3, a0, -18
; RV64-NEXT:    add a1, a1, a2
; RV64-NEXT:    sh a1, 0(a0)
; RV64-NEXT:    mv a0, a3
; RV64-NEXT:    ret
;
; RV64-ZISXIA-LABEL: shia:
; RV64-ZISXIA:       # %bb.0:
; RV64-ZISXIA-NEXT:    add a1, a1, a2
; RV64-ZISXIA-NEXT:    shia a1, (a0), -9
; RV64-ZISXIA-NEXT:    ret
  %addr.1 = getelementptr i16, ptr %base, iXLen -9
  %res = add i16 %a, %b
  store i16 %res, ptr %base
  ret ptr %addr.1
}

define ptr @swia(ptr %base, i32 %a, i32 %b) {
; RV32-LABEL: swia:
; RV32:       # %bb.0:
; RV32-NEXT:    addi a3, a0, 32
; RV32-NEXT:    add a1, a1, a2
; RV32-NEXT:    sw a1, 0(a0)
; RV32-NEXT:    mv a0, a3
; RV32-NEXT:    ret
;
; RV32-ZISXIA-LABEL: swia:
; RV32-ZISXIA:       # %bb.0:
; RV32-ZISXIA-NEXT:    add a1, a1, a2
; RV32-ZISXIA-NEXT:    swia a1, (a0), 8
; RV32-ZISXIA-NEXT:    ret
;
; RV64-LABEL: swia:
; RV64:       # %bb.0:
; RV64-NEXT:    addi a3, a0, 32
; RV64-NEXT:    add a1, a1, a2
; RV64-NEXT:    sw a1, 0(a0)
; RV64-NEXT:    mv a0, a3
; RV64-NEXT:    ret
;
; RV64-ZISXIA-LABEL: swia:
; RV64-ZISXIA:       # %bb.0:
; RV64-ZISXIA-NEXT:    add a1, a1, a2
; RV64-ZISXIA-NEXT:    swia a1, (a0), 8
; RV64-ZISXIA-NEXT:    ret
  %addr.1 = getelementptr i32, ptr %base, iXLen 8
  %res = add i32 %a, %b
  store i32 %res, ptr %base
  ret ptr %addr.1
}

define ptr @sdia(ptr %base, i64 %a, i64 %b) {
; RV32-LABEL: sdia:
; RV32:       # %bb.0:
; RV32-NEXT:    addi a5, a0, 64
; RV32-NEXT:    add a2, a2, a4
; RV32-NEXT:    add a3, a1, a3
; RV32-NEXT:    sltu a1, a3, a1
; RV32-NEXT:    add a1, a2, a1
; RV32-NEXT:    sw a3, 0(a0)
; RV32-NEXT:    sw a1, 4(a0)
; RV32-NEXT:    mv a0, a5
; RV32-NEXT:    ret
;
; RV32-ZISXIA-LABEL: sdia:
; RV32-ZISXIA:       # %bb.0:
; RV32-ZISXIA-NEXT:    addi a5, a0, 64
; RV32-ZISXIA-NEXT:    add a2, a2, a4
; RV32-ZISXIA-NEXT:    add a3, a1, a3
; RV32-ZISXIA-NEXT:    sltu a1, a3, a1
; RV32-ZISXIA-NEXT:    add a1, a2, a1
; RV32-ZISXIA-NEXT:    sw a3, 0(a0)
; RV32-ZISXIA-NEXT:    sw a1, 4(a0)
; RV32-ZISXIA-NEXT:    mv a0, a5
; RV32-ZISXIA-NEXT:    ret
;
; RV64-LABEL: sdia:
; RV64:       # %bb.0:
; RV64-NEXT:    addi a3, a0, 64
; RV64-NEXT:    add a1, a1, a2
; RV64-NEXT:    sd a1, 0(a0)
; RV64-NEXT:    mv a0, a3
; RV64-NEXT:    ret
;
; RV64-ZISXIA-LABEL: sdia:
; RV64-ZISXIA:       # %bb.0:
; RV64-ZISXIA-NEXT:    add a1, a1, a2
; RV64-ZISXIA-NEXT:    sdia a1, (a0), 8
; RV64-ZISXIA-NEXT:    ret
  %addr.1 = getelementptr i64, ptr %base, iXLen 8
  %res = add i64 %a, %b
  store i64 %res, ptr %base
  ret ptr %addr.1
}
