; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: sed 's/iXLen/i32/g' %s | llc -mtriple=riscv32 -verify-machineinstrs \
; RUN:   | FileCheck -check-prefix=RV32 %s
; RUN: sed 's/iXLen/i32/g' %s | llc -mtriple=riscv32 -mattr=+zisxib -verify-machineinstrs \
; RUN:   | FileCheck -check-prefix=RV32-ZISXIB %s
; RUN: sed 's/iXLen/i64/g' %s | llc -mtriple=riscv64 -verify-machineinstrs \
; RUN:   | FileCheck -check-prefix=RV64 %s
; RUN: sed 's/iXLen/i64/g' %s | llc -mtriple=riscv64 -mattr=+zisxib -verify-machineinstrs \
; RUN:   | FileCheck -check-prefix=RV64-ZISXIB %s

define ptr @sbib(ptr %base, i8 %a, i8 %b) {
; RV32-LABEL: sbib:
; RV32:       # %bb.0:
; RV32-NEXT:    addi a3, a0, 1
; RV32-NEXT:    add a1, a1, a2
; RV32-NEXT:    sb a1, 1(a0)
; RV32-NEXT:    mv a0, a3
; RV32-NEXT:    ret
;
; RV32-ZISXIB-LABEL: sbib:
; RV32-ZISXIB:       # %bb.0:
; RV32-ZISXIB-NEXT:    add a1, a1, a2
; RV32-ZISXIB-NEXT:    sbib a1, (a0), 1
; RV32-ZISXIB-NEXT:    ret
;
; RV64-LABEL: sbib:
; RV64:       # %bb.0:
; RV64-NEXT:    addi a3, a0, 1
; RV64-NEXT:    add a1, a1, a2
; RV64-NEXT:    sb a1, 1(a0)
; RV64-NEXT:    mv a0, a3
; RV64-NEXT:    ret
;
; RV64-ZISXIB-LABEL: sbib:
; RV64-ZISXIB:       # %bb.0:
; RV64-ZISXIB-NEXT:    add a1, a1, a2
; RV64-ZISXIB-NEXT:    sbib a1, (a0), 1
; RV64-ZISXIB-NEXT:    ret
  %addr.1 = getelementptr i8, ptr %base, iXLen 1
  %res = add i8 %a, %b
  store i8 %res, ptr %addr.1
  ret ptr %addr.1
}

define ptr @shib(ptr %base, i16 %a, i16 %b) {
; RV32-LABEL: shib:
; RV32:       # %bb.0:
; RV32-NEXT:    addi a3, a0, 2
; RV32-NEXT:    add a1, a1, a2
; RV32-NEXT:    sh a1, 2(a0)
; RV32-NEXT:    mv a0, a3
; RV32-NEXT:    ret
;
; RV32-ZISXIB-LABEL: shib:
; RV32-ZISXIB:       # %bb.0:
; RV32-ZISXIB-NEXT:    add a1, a1, a2
; RV32-ZISXIB-NEXT:    shib a1, (a0), 1
; RV32-ZISXIB-NEXT:    ret
;
; RV64-LABEL: shib:
; RV64:       # %bb.0:
; RV64-NEXT:    addi a3, a0, 2
; RV64-NEXT:    add a1, a1, a2
; RV64-NEXT:    sh a1, 2(a0)
; RV64-NEXT:    mv a0, a3
; RV64-NEXT:    ret
;
; RV64-ZISXIB-LABEL: shib:
; RV64-ZISXIB:       # %bb.0:
; RV64-ZISXIB-NEXT:    add a1, a1, a2
; RV64-ZISXIB-NEXT:    shib a1, (a0), 1
; RV64-ZISXIB-NEXT:    ret
  %addr.1 = getelementptr i16, ptr %base, iXLen 1
  %res = add i16 %a, %b
  store i16 %res, ptr %addr.1
  ret ptr %addr.1
}

define ptr @swib(ptr %base, i32 %a, i32 %b) {
; RV32-LABEL: swib:
; RV32:       # %bb.0:
; RV32-NEXT:    addi a3, a0, -36
; RV32-NEXT:    add a1, a1, a2
; RV32-NEXT:    sw a1, -36(a0)
; RV32-NEXT:    mv a0, a3
; RV32-NEXT:    ret
;
; RV32-ZISXIB-LABEL: swib:
; RV32-ZISXIB:       # %bb.0:
; RV32-ZISXIB-NEXT:    add a1, a1, a2
; RV32-ZISXIB-NEXT:    swib a1, (a0), -9
; RV32-ZISXIB-NEXT:    ret
;
; RV64-LABEL: swib:
; RV64:       # %bb.0:
; RV64-NEXT:    addi a3, a0, -36
; RV64-NEXT:    add a1, a1, a2
; RV64-NEXT:    sw a1, -36(a0)
; RV64-NEXT:    mv a0, a3
; RV64-NEXT:    ret
;
; RV64-ZISXIB-LABEL: swib:
; RV64-ZISXIB:       # %bb.0:
; RV64-ZISXIB-NEXT:    add a1, a1, a2
; RV64-ZISXIB-NEXT:    swib a1, (a0), -9
; RV64-ZISXIB-NEXT:    ret
  %addr.1 = getelementptr i32, ptr %base, iXLen -9
  %res = add i32 %a, %b
  store i32 %res, ptr %addr.1
  ret ptr %addr.1
}

define ptr @sdib(ptr %base, i64 %a, i64 %b) {
; RV32-LABEL: sdib:
; RV32:       # %bb.0:
; RV32-NEXT:    addi a5, a0, 8
; RV32-NEXT:    add a2, a2, a4
; RV32-NEXT:    add a3, a1, a3
; RV32-NEXT:    sltu a1, a3, a1
; RV32-NEXT:    add a1, a2, a1
; RV32-NEXT:    sw a3, 8(a0)
; RV32-NEXT:    sw a1, 12(a0)
; RV32-NEXT:    mv a0, a5
; RV32-NEXT:    ret
;
; RV32-ZISXIB-LABEL: sdib:
; RV32-ZISXIB:       # %bb.0:
; RV32-ZISXIB-NEXT:    add a2, a2, a4
; RV32-ZISXIB-NEXT:    add a3, a1, a3
; RV32-ZISXIB-NEXT:    sltu a1, a3, a1
; RV32-ZISXIB-NEXT:    add a1, a2, a1
; RV32-ZISXIB-NEXT:    swib a3, (a0), 2
; RV32-ZISXIB-NEXT:    sw a1, 4(a0)
; RV32-ZISXIB-NEXT:    ret
;
; RV64-LABEL: sdib:
; RV64:       # %bb.0:
; RV64-NEXT:    addi a3, a0, 8
; RV64-NEXT:    add a1, a1, a2
; RV64-NEXT:    sd a1, 8(a0)
; RV64-NEXT:    mv a0, a3
; RV64-NEXT:    ret
;
; RV64-ZISXIB-LABEL: sdib:
; RV64-ZISXIB:       # %bb.0:
; RV64-ZISXIB-NEXT:    add a1, a1, a2
; RV64-ZISXIB-NEXT:    sdib a1, (a0), 1
; RV64-ZISXIB-NEXT:    ret
  %addr.1 = getelementptr i64, ptr %base, iXLen 1
  %res = add i64 %a, %b
  store i64 %res, ptr %addr.1
  ret ptr %addr.1
}
