; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --filter-out-after "^scalar.ph:" --version 5
; RUN: opt < %s -passes=loop-vectorize -mtriple=riscv64 \
; RUN:   -mattr=+v,+experimental-zvcd -enable-histogram-loop-vectorization -S \
; RUN:   | FileCheck %s --check-prefix=HISTOGRAM
; RUN: opt < %s -passes=loop-vectorize -mtriple=riscv64 -mattr=+v \
; RUN:   -enable-histogram-loop-vectorization -S | FileCheck %s --check-prefix=DISABLED

;; Based on the following C code:
;;
;; void simple_histogram(int *buckets, unsigned *indices, int N) {
;;   for (int i = 0; i < N; ++i)
;;     buckets[indices[i]]++;
;; }
;;
;; With Zvcd the loop vectorizer finds a finite cost for the histogram
;; intrinsic and emits it (later lowered to gather + vconflictcnt.v + ordered
;; scatter).  Without Zvcd the RISC-V cost model returns an invalid cost, so
;; the loop stays scalar and no intrinsic is generated.

define void @simple_histogram(ptr noalias %buckets, ptr readonly %indices, i64 %N) #0 {
; HISTOGRAM-LABEL: define void @simple_histogram(
; HISTOGRAM-SAME: ptr noalias [[BUCKETS:%.*]], ptr readonly [[INDICES:%.*]], i64 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; HISTOGRAM-NEXT:  [[ENTRY:.*:]]
; HISTOGRAM-NEXT:    br label %[[VECTOR_PH:.*]]
; HISTOGRAM:       [[VECTOR_PH]]:
; HISTOGRAM-NEXT:    br label %[[VECTOR_BODY:.*]]
; HISTOGRAM:       [[VECTOR_BODY]]:
; HISTOGRAM-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[CURRENT_ITERATION_NEXT:%.*]], %[[VECTOR_BODY]] ]
; HISTOGRAM-NEXT:    [[AVL:%.*]] = phi i64 [ [[N]], %[[VECTOR_PH]] ], [ [[AVL_NEXT:%.*]], %[[VECTOR_BODY]] ]
; HISTOGRAM-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[AVL]], i32 4, i1 true)
; HISTOGRAM-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i32> poison, i32 [[TMP0]], i64 0
; HISTOGRAM-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 4 x i32> [[BROADCAST_SPLATINSERT]], <vscale x 4 x i32> poison, <vscale x 4 x i32> zeroinitializer
; HISTOGRAM-NEXT:    [[TMP1:%.*]] = call <vscale x 4 x i32> @llvm.stepvector.nxv4i32()
; HISTOGRAM-NEXT:    [[TMP2:%.*]] = icmp ult <vscale x 4 x i32> [[TMP1]], [[BROADCAST_SPLAT]]
; HISTOGRAM-NEXT:    [[TMP3:%.*]] = getelementptr inbounds i32, ptr [[INDICES]], i64 [[INDEX]]
; HISTOGRAM-NEXT:    [[VP_OP_LOAD:%.*]] = call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr align 4 [[TMP3]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP0]])
; HISTOGRAM-NEXT:    [[TMP4:%.*]] = zext <vscale x 4 x i32> [[VP_OP_LOAD]] to <vscale x 4 x i64>
; HISTOGRAM-NEXT:    [[WIDE_GEP:%.*]] = getelementptr inbounds i32, ptr [[BUCKETS]], <vscale x 4 x i64> [[TMP4]]
; HISTOGRAM-NEXT:    call void @llvm.experimental.vector.histogram.add.nxv4p0.i32(<vscale x 4 x ptr> [[WIDE_GEP]], i32 1, <vscale x 4 x i1> [[TMP2]])
; HISTOGRAM-NEXT:    [[TMP5:%.*]] = zext i32 [[TMP0]] to i64
; HISTOGRAM-NEXT:    [[CURRENT_ITERATION_NEXT]] = add i64 [[TMP5]], [[INDEX]]
; HISTOGRAM-NEXT:    [[AVL_NEXT]] = sub nuw i64 [[AVL]], [[TMP5]]
; HISTOGRAM-NEXT:    [[TMP6:%.*]] = icmp eq i64 [[AVL_NEXT]], 0
; HISTOGRAM-NEXT:    br i1 [[TMP6]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; HISTOGRAM:       [[MIDDLE_BLOCK]]:
; HISTOGRAM-NEXT:    br label %[[FOR_EXIT:.*]]
; HISTOGRAM:       [[FOR_EXIT]]:
; HISTOGRAM-NEXT:    ret void
;
; DISABLED-LABEL: define void @simple_histogram(
; DISABLED-SAME: ptr noalias [[BUCKETS:%.*]], ptr readonly [[INDICES:%.*]], i64 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; DISABLED-NEXT:  [[ENTRY:.*]]:
; DISABLED-NEXT:    br label %[[FOR_BODY:.*]]
; DISABLED:       [[FOR_BODY]]:
; DISABLED-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[FOR_BODY]] ]
; DISABLED-NEXT:    [[GEP_INDICES:%.*]] = getelementptr inbounds i32, ptr [[INDICES]], i64 [[IV]]
; DISABLED-NEXT:    [[L_IDX:%.*]] = load i32, ptr [[GEP_INDICES]], align 4
; DISABLED-NEXT:    [[IDXPROM1:%.*]] = zext i32 [[L_IDX]] to i64
; DISABLED-NEXT:    [[GEP_BUCKET:%.*]] = getelementptr inbounds i32, ptr [[BUCKETS]], i64 [[IDXPROM1]]
; DISABLED-NEXT:    [[L_BUCKET:%.*]] = load i32, ptr [[GEP_BUCKET]], align 4
; DISABLED-NEXT:    [[INC:%.*]] = add nsw i32 [[L_BUCKET]], 1
; DISABLED-NEXT:    store i32 [[INC]], ptr [[GEP_BUCKET]], align 4
; DISABLED-NEXT:    [[IV_NEXT]] = add nuw nsw i64 [[IV]], 1
; DISABLED-NEXT:    [[EXITCOND:%.*]] = icmp eq i64 [[IV_NEXT]], [[N]]
; DISABLED-NEXT:    br i1 [[EXITCOND]], label %[[FOR_EXIT:.*]], label %[[FOR_BODY]]
; DISABLED:       [[FOR_EXIT]]:
; DISABLED-NEXT:    ret void
;
entry:
  br label %for.body

for.body:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.body ]
  %gep.indices = getelementptr inbounds i32, ptr %indices, i64 %iv
  %l.idx = load i32, ptr %gep.indices, align 4
  %idxprom1 = zext i32 %l.idx to i64
  %gep.bucket = getelementptr inbounds i32, ptr %buckets, i64 %idxprom1
  %l.bucket = load i32, ptr %gep.bucket, align 4
  %inc = add nsw i32 %l.bucket, 1
  store i32 %inc, ptr %gep.bucket, align 4
  %iv.next = add nuw nsw i64 %iv, 1
  %exitcond = icmp eq i64 %iv.next, %N
  br i1 %exitcond, label %for.exit, label %for.body

for.exit:
  ret void
}

attributes #0 = { "target-features"="+v" }
;.
; HISTOGRAM: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; HISTOGRAM: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; HISTOGRAM: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
;.
