; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv64 -mattr=+v,+experimental-zvcd -target-abi=lp64d \
; RUN:   < %s | FileCheck %s --check-prefixes=RV64

;; i64 histogram buckets are only lowered on RV64, where the i64 increment is a
;; legal scalar.  The lowering uses the Zvcd vconflictcnt.v conflict count.

define void @histogram_add_i64(<vscale x 2 x ptr> %buckets, i64 %inc, <vscale x 2 x i1> %mask) {
; RV64-LABEL: histogram_add_i64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a1, zero, e64, m2, ta, mu
; RV64-NEXT:    vmv.v.i v10, 0
; RV64-NEXT:    vluxei64.v v10, (zero), v8, v0.t
; RV64-NEXT:    vsetvli zero, zero, e64, m2, ta, ma
; RV64-NEXT:    vconflictcnt.v v12, v8, v0.t
; RV64-NEXT:    vmadd.vx v12, a0, v10
; RV64-NEXT:    vsoxei64.v v12, (zero), v8, v0.t
; RV64-NEXT:    ret
  call void @llvm.experimental.vector.histogram.add.nxv2p0.i64(<vscale x 2 x ptr> %buckets, i64 %inc, <vscale x 2 x i1> %mask)
  ret void
}
