; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv32 -mattr=+v,+experimental-zvcd -target-abi=ilp32d \
; RUN:   -riscv-lower-histogram-unordered-scatter < %s \
; RUN:   | FileCheck %s --check-prefixes=RV32
; RUN: llc -mtriple=riscv64 -mattr=+v,+experimental-zvcd -target-abi=lp64d \
; RUN:   -riscv-lower-histogram-unordered-scatter < %s \
; RUN:   | FileCheck %s --check-prefixes=RV64

;; With -riscv-lower-histogram-unordered-scatter the 'add' histogram lowering
;; uses vconflictlast.m to keep only the unique highest-index active writer of
;; each equal-value group (vmand.mm intersects it with the execution mask).  On
;; that lane vconflictcnt.v already holds the group total, so old + count*inc
;; is the final value and the selected lanes target distinct buckets.  The
;; store no longer needs the ordered vsoxei and uses the unordered vsuxei.

define void @histogram_add_i32(<vscale x 2 x ptr> %buckets, i32 %inc, <vscale x 2 x i1> %mask) {
; RV32-LABEL: histogram_add_i32:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a1, zero, e32, m1, ta, mu
; RV32-NEXT:    vmv.v.i v9, 0
; RV32-NEXT:    vluxei32.v v9, (zero), v8, v0.t
; RV32-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; RV32-NEXT:    vconflictcnt.v v10, v8, v0.t
; RV32-NEXT:    vconflictlast.m v11, v8, v0.t
; RV32-NEXT:    vmand.mm v0, v0, v11
; RV32-NEXT:    vmadd.vx v10, a0, v9
; RV32-NEXT:    vsuxei32.v v10, (zero), v8, v0.t
; RV32-NEXT:    ret
;
; RV64-LABEL: histogram_add_i32:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a1, zero, e32, m1, ta, mu
; RV64-NEXT:    vmv.v.i v10, 0
; RV64-NEXT:    vnsrl.wi v11, v8, 0
; RV64-NEXT:    vluxei64.v v10, (zero), v8, v0.t
; RV64-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; RV64-NEXT:    vconflictcnt.v v12, v11, v0.t
; RV64-NEXT:    vconflictlast.m v13, v11, v0.t
; RV64-NEXT:    vmand.mm v0, v0, v13
; RV64-NEXT:    vmadd.vx v12, a0, v10
; RV64-NEXT:    vsuxei64.v v12, (zero), v8, v0.t
; RV64-NEXT:    ret
  call void @llvm.experimental.vector.histogram.add.nxv2p0.i32(<vscale x 2 x ptr> %buckets, i32 %inc, <vscale x 2 x i1> %mask)
  ret void
}

define void @histogram_add_i32_nxv4(<vscale x 4 x ptr> %buckets, i32 %inc, <vscale x 4 x i1> %mask) {
; RV32-LABEL: histogram_add_i32_nxv4:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a1, zero, e32, m2, ta, mu
; RV32-NEXT:    vmv.v.i v10, 0
; RV32-NEXT:    vluxei32.v v10, (zero), v8, v0.t
; RV32-NEXT:    vsetvli zero, zero, e32, m2, ta, ma
; RV32-NEXT:    vconflictcnt.v v12, v8, v0.t
; RV32-NEXT:    vconflictlast.m v14, v8, v0.t
; RV32-NEXT:    vmadd.vx v12, a0, v10
; RV32-NEXT:    vmand.mm v0, v0, v14
; RV32-NEXT:    vsuxei32.v v12, (zero), v8, v0.t
; RV32-NEXT:    ret
;
; RV64-LABEL: histogram_add_i32_nxv4:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a1, zero, e32, m2, ta, mu
; RV64-NEXT:    vmv.v.i v12, 0
; RV64-NEXT:    vnsrl.wi v14, v8, 0
; RV64-NEXT:    vluxei64.v v12, (zero), v8, v0.t
; RV64-NEXT:    vsetvli zero, zero, e32, m2, ta, ma
; RV64-NEXT:    vconflictcnt.v v16, v14, v0.t
; RV64-NEXT:    vconflictlast.m v18, v14, v0.t
; RV64-NEXT:    vmadd.vx v16, a0, v12
; RV64-NEXT:    vmand.mm v0, v0, v18
; RV64-NEXT:    vsuxei64.v v16, (zero), v8, v0.t
; RV64-NEXT:    ret
  call void @llvm.experimental.vector.histogram.add.nxv4p0.i32(<vscale x 4 x ptr> %buckets, i32 %inc, <vscale x 4 x i1> %mask)
  ret void
}
