; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: sed 's/iXLen/i32/g' %s | llc -mtriple=riscv32 -mattr=+v,+experimental-zvcd \
; RUN:   -verify-machineinstrs | FileCheck %s --check-prefixes=CHECK,RV32
; RUN: sed 's/iXLen/i64/g' %s | llc -mtriple=riscv64 -mattr=+v,+experimental-zvcd \
; RUN:   -verify-machineinstrs | FileCheck %s --check-prefixes=CHECK,RV64

define <vscale x 1 x i1> @test_vconflictlast_i32mf2(<vscale x 1 x i1> %passthru, <vscale x 1 x i32> %arg, iXLen %vl) nounwind {
; CHECK-LABEL: test_vconflictlast_i32mf2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, mf2, tu, ma
; CHECK-NEXT:    vconflictlast.m v0, v8
; CHECK-NEXT:    ret
  %a = call <vscale x 1 x i1> @llvm.riscv.vconflictlast(
    <vscale x 1 x i1> %passthru,
    <vscale x 1 x i32> %arg,
    iXLen %vl)
  ret <vscale x 1 x i1> %a
}

define <vscale x 1 x i1> @test_vconflictlast_mask_i32mf2(<vscale x 1 x i1> %passthru, <vscale x 1 x i32> %arg, <vscale x 1 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vconflictlast_mask_i32mf2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 1, e8, m1, ta, ma
; CHECK-NEXT:    vmv1r.v v10, v0
; CHECK-NEXT:    vmv1r.v v0, v9
; CHECK-NEXT:    vsetvli zero, a0, e32, mf2, ta, mu
; CHECK-NEXT:    vconflictlast.m v10, v8, v0.t
; CHECK-NEXT:    vmv1r.v v0, v10
; CHECK-NEXT:    ret
  %a = call <vscale x 1 x i1> @llvm.riscv.vconflictlast.mask(
    <vscale x 1 x i1> %passthru,
    <vscale x 1 x i32> %arg,
    <vscale x 1 x i1> %mask,
    iXLen %vl)
  ret <vscale x 1 x i1> %a
}

define <vscale x 2 x i1> @test_vconflictlast_i32m1(<vscale x 2 x i1> %passthru, <vscale x 2 x i32> %arg, iXLen %vl) nounwind {
; CHECK-LABEL: test_vconflictlast_i32m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m1, tu, ma
; CHECK-NEXT:    vconflictlast.m v0, v8
; CHECK-NEXT:    ret
  %a = call <vscale x 2 x i1> @llvm.riscv.vconflictlast(
    <vscale x 2 x i1> %passthru,
    <vscale x 2 x i32> %arg,
    iXLen %vl)
  ret <vscale x 2 x i1> %a
}

define <vscale x 4 x i1> @test_vconflictlast_i32m2(<vscale x 4 x i1> %passthru, <vscale x 4 x i32> %arg, iXLen %vl) nounwind {
; CHECK-LABEL: test_vconflictlast_i32m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m2, tu, ma
; CHECK-NEXT:    vconflictlast.m v0, v8
; CHECK-NEXT:    ret
  %a = call <vscale x 4 x i1> @llvm.riscv.vconflictlast(
    <vscale x 4 x i1> %passthru,
    <vscale x 4 x i32> %arg,
    iXLen %vl)
  ret <vscale x 4 x i1> %a
}

define <vscale x 1 x i1> @test_vconflictlast_i64m1(<vscale x 1 x i1> %passthru, <vscale x 1 x i64> %arg, iXLen %vl) nounwind {
; CHECK-LABEL: test_vconflictlast_i64m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, ma
; CHECK-NEXT:    vconflictlast.m v0, v8
; CHECK-NEXT:    ret
  %a = call <vscale x 1 x i1> @llvm.riscv.vconflictlast(
    <vscale x 1 x i1> %passthru,
    <vscale x 1 x i64> %arg,
    iXLen %vl)
  ret <vscale x 1 x i1> %a
}

define <vscale x 2 x i1> @test_vconflictlast_mask_i64m2(<vscale x 2 x i1> %passthru, <vscale x 2 x i64> %arg, <vscale x 2 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vconflictlast_mask_i64m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 1, e8, m1, ta, ma
; CHECK-NEXT:    vmv1r.v v11, v0
; CHECK-NEXT:    vmv1r.v v0, v10
; CHECK-NEXT:    vsetvli zero, a0, e64, m2, ta, mu
; CHECK-NEXT:    vconflictlast.m v11, v8, v0.t
; CHECK-NEXT:    vmv1r.v v0, v11
; CHECK-NEXT:    ret
  %a = call <vscale x 2 x i1> @llvm.riscv.vconflictlast.mask(
    <vscale x 2 x i1> %passthru,
    <vscale x 2 x i64> %arg,
    <vscale x 2 x i1> %mask,
    iXLen %vl)
  ret <vscale x 2 x i1> %a
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; RV32: {{.*}}
; RV64: {{.*}}
